// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package pulpissimo_padframe_all_pads_config_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 9;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    struct packed {
      logic [15:0] q;
    } hw_version;
    struct packed {
      logic [15:0] q;
    } padcount;
  } pulpissimo_padframe_all_pads_config_reg2hw_info_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } pull_en;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io00_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io00_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } pull_en;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io01_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io01_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } pull_en;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io02_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io02_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } pull_en;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io03_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io03_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } pull_en;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io04_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io04_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } pull_en;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io05_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io05_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } pull_en;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io06_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io06_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } pull_en;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io07_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io07_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } pull_en;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io08_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io08_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } pull_en;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io09_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io09_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } pull_en;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io10_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io10_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } pull_en;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io11_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io11_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } pull_en;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io12_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io12_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } pull_en;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io13_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io13_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } pull_en;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io14_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io14_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } pull_en;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io15_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io15_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } pull_en;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io16_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io16_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } pull_en;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io17_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io17_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } pull_en;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io18_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io18_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } pull_en;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io19_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io19_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } pull_en;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io20_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io20_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } pull_en;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io21_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io21_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } pull_en;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io22_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io22_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } pull_en;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io23_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io23_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } pull_en;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io24_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io24_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } pull_en;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io25_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io25_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } pull_en;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io26_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io26_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } pull_en;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io27_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io27_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } pull_en;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io28_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io28_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } pull_en;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io29_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io29_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } pull_en;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io30_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io30_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } pull_en;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io31_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io31_mux_sel_reg_t;

  // Register -> HW type
  typedef struct packed {
    pulpissimo_padframe_all_pads_config_reg2hw_info_reg_t info; // [351:320]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io00_cfg_reg_t pad_io00_cfg; // [319:316]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io00_mux_sel_reg_t pad_io00_mux_sel; // [315:310]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io01_cfg_reg_t pad_io01_cfg; // [309:306]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io01_mux_sel_reg_t pad_io01_mux_sel; // [305:300]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io02_cfg_reg_t pad_io02_cfg; // [299:296]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io02_mux_sel_reg_t pad_io02_mux_sel; // [295:290]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io03_cfg_reg_t pad_io03_cfg; // [289:286]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io03_mux_sel_reg_t pad_io03_mux_sel; // [285:280]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io04_cfg_reg_t pad_io04_cfg; // [279:276]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io04_mux_sel_reg_t pad_io04_mux_sel; // [275:270]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io05_cfg_reg_t pad_io05_cfg; // [269:266]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io05_mux_sel_reg_t pad_io05_mux_sel; // [265:260]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io06_cfg_reg_t pad_io06_cfg; // [259:256]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io06_mux_sel_reg_t pad_io06_mux_sel; // [255:250]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io07_cfg_reg_t pad_io07_cfg; // [249:246]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io07_mux_sel_reg_t pad_io07_mux_sel; // [245:240]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io08_cfg_reg_t pad_io08_cfg; // [239:236]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io08_mux_sel_reg_t pad_io08_mux_sel; // [235:230]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io09_cfg_reg_t pad_io09_cfg; // [229:226]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io09_mux_sel_reg_t pad_io09_mux_sel; // [225:220]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io10_cfg_reg_t pad_io10_cfg; // [219:216]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io10_mux_sel_reg_t pad_io10_mux_sel; // [215:210]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io11_cfg_reg_t pad_io11_cfg; // [209:206]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io11_mux_sel_reg_t pad_io11_mux_sel; // [205:200]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io12_cfg_reg_t pad_io12_cfg; // [199:196]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io12_mux_sel_reg_t pad_io12_mux_sel; // [195:190]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io13_cfg_reg_t pad_io13_cfg; // [189:186]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io13_mux_sel_reg_t pad_io13_mux_sel; // [185:180]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io14_cfg_reg_t pad_io14_cfg; // [179:176]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io14_mux_sel_reg_t pad_io14_mux_sel; // [175:170]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io15_cfg_reg_t pad_io15_cfg; // [169:166]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io15_mux_sel_reg_t pad_io15_mux_sel; // [165:160]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io16_cfg_reg_t pad_io16_cfg; // [159:156]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io16_mux_sel_reg_t pad_io16_mux_sel; // [155:150]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io17_cfg_reg_t pad_io17_cfg; // [149:146]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io17_mux_sel_reg_t pad_io17_mux_sel; // [145:140]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io18_cfg_reg_t pad_io18_cfg; // [139:136]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io18_mux_sel_reg_t pad_io18_mux_sel; // [135:130]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io19_cfg_reg_t pad_io19_cfg; // [129:126]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io19_mux_sel_reg_t pad_io19_mux_sel; // [125:120]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io20_cfg_reg_t pad_io20_cfg; // [119:116]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io20_mux_sel_reg_t pad_io20_mux_sel; // [115:110]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io21_cfg_reg_t pad_io21_cfg; // [109:106]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io21_mux_sel_reg_t pad_io21_mux_sel; // [105:100]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io22_cfg_reg_t pad_io22_cfg; // [99:96]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io22_mux_sel_reg_t pad_io22_mux_sel; // [95:90]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io23_cfg_reg_t pad_io23_cfg; // [89:86]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io23_mux_sel_reg_t pad_io23_mux_sel; // [85:80]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io24_cfg_reg_t pad_io24_cfg; // [79:76]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io24_mux_sel_reg_t pad_io24_mux_sel; // [75:70]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io25_cfg_reg_t pad_io25_cfg; // [69:66]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io25_mux_sel_reg_t pad_io25_mux_sel; // [65:60]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io26_cfg_reg_t pad_io26_cfg; // [59:56]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io26_mux_sel_reg_t pad_io26_mux_sel; // [55:50]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io27_cfg_reg_t pad_io27_cfg; // [49:46]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io27_mux_sel_reg_t pad_io27_mux_sel; // [45:40]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io28_cfg_reg_t pad_io28_cfg; // [39:36]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io28_mux_sel_reg_t pad_io28_mux_sel; // [35:30]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io29_cfg_reg_t pad_io29_cfg; // [29:26]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io29_mux_sel_reg_t pad_io29_mux_sel; // [25:20]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io30_cfg_reg_t pad_io30_cfg; // [19:16]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io30_mux_sel_reg_t pad_io30_mux_sel; // [15:10]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io31_cfg_reg_t pad_io31_cfg; // [9:6]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io31_mux_sel_reg_t pad_io31_mux_sel; // [5:0]
  } pulpissimo_padframe_all_pads_config_reg2hw_t;

  // Register offsets
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_INFO_OFFSET = 9'h 0;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO00_CFG_OFFSET = 9'h 4;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO00_MUX_SEL_OFFSET = 9'h 8;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO01_CFG_OFFSET = 9'h c;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO01_MUX_SEL_OFFSET = 9'h 10;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO02_CFG_OFFSET = 9'h 14;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO02_MUX_SEL_OFFSET = 9'h 18;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO03_CFG_OFFSET = 9'h 1c;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO03_MUX_SEL_OFFSET = 9'h 20;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO04_CFG_OFFSET = 9'h 24;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO04_MUX_SEL_OFFSET = 9'h 28;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO05_CFG_OFFSET = 9'h 2c;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO05_MUX_SEL_OFFSET = 9'h 30;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO06_CFG_OFFSET = 9'h 34;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO06_MUX_SEL_OFFSET = 9'h 38;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO07_CFG_OFFSET = 9'h 3c;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO07_MUX_SEL_OFFSET = 9'h 40;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO08_CFG_OFFSET = 9'h 44;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO08_MUX_SEL_OFFSET = 9'h 48;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO09_CFG_OFFSET = 9'h 4c;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO09_MUX_SEL_OFFSET = 9'h 50;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO10_CFG_OFFSET = 9'h 54;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO10_MUX_SEL_OFFSET = 9'h 58;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO11_CFG_OFFSET = 9'h 5c;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO11_MUX_SEL_OFFSET = 9'h 60;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO12_CFG_OFFSET = 9'h 64;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO12_MUX_SEL_OFFSET = 9'h 68;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO13_CFG_OFFSET = 9'h 6c;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO13_MUX_SEL_OFFSET = 9'h 70;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO14_CFG_OFFSET = 9'h 74;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO14_MUX_SEL_OFFSET = 9'h 78;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO15_CFG_OFFSET = 9'h 7c;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO15_MUX_SEL_OFFSET = 9'h 80;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO16_CFG_OFFSET = 9'h 84;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO16_MUX_SEL_OFFSET = 9'h 88;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO17_CFG_OFFSET = 9'h 8c;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO17_MUX_SEL_OFFSET = 9'h 90;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO18_CFG_OFFSET = 9'h 94;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO18_MUX_SEL_OFFSET = 9'h 98;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO19_CFG_OFFSET = 9'h 9c;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO19_MUX_SEL_OFFSET = 9'h a0;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO20_CFG_OFFSET = 9'h a4;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO20_MUX_SEL_OFFSET = 9'h a8;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO21_CFG_OFFSET = 9'h ac;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO21_MUX_SEL_OFFSET = 9'h b0;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO22_CFG_OFFSET = 9'h b4;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO22_MUX_SEL_OFFSET = 9'h b8;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO23_CFG_OFFSET = 9'h bc;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO23_MUX_SEL_OFFSET = 9'h c0;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO24_CFG_OFFSET = 9'h c4;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO24_MUX_SEL_OFFSET = 9'h c8;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO25_CFG_OFFSET = 9'h cc;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO25_MUX_SEL_OFFSET = 9'h d0;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO26_CFG_OFFSET = 9'h d4;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO26_MUX_SEL_OFFSET = 9'h d8;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO27_CFG_OFFSET = 9'h dc;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO27_MUX_SEL_OFFSET = 9'h e0;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO28_CFG_OFFSET = 9'h e4;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO28_MUX_SEL_OFFSET = 9'h e8;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO29_CFG_OFFSET = 9'h ec;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO29_MUX_SEL_OFFSET = 9'h f0;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO30_CFG_OFFSET = 9'h f4;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO30_MUX_SEL_OFFSET = 9'h f8;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO31_CFG_OFFSET = 9'h fc;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO31_MUX_SEL_OFFSET = 9'h 100;

  // Register index
  typedef enum int {
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_INFO,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO00_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO00_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO01_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO01_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO02_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO02_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO03_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO03_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO04_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO04_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO05_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO05_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO06_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO06_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO07_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO07_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO08_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO08_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO09_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO09_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO10_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO10_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO11_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO11_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO12_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO12_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO13_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO13_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO14_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO14_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO15_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO15_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO16_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO16_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO17_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO17_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO18_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO18_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO19_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO19_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO20_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO20_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO21_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO21_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO22_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO22_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO23_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO23_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO24_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO24_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO25_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO25_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO26_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO26_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO27_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO27_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO28_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO28_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO29_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO29_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO30_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO30_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO31_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO31_MUX_SEL
  } pulpissimo_padframe_all_pads_config_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PERMIT [65] = '{
    4'b 1111, // index[ 0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_INFO
    4'b 0001, // index[ 1] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO00_CFG
    4'b 0001, // index[ 2] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO00_MUX_SEL
    4'b 0001, // index[ 3] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO01_CFG
    4'b 0001, // index[ 4] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO01_MUX_SEL
    4'b 0001, // index[ 5] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO02_CFG
    4'b 0001, // index[ 6] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO02_MUX_SEL
    4'b 0001, // index[ 7] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO03_CFG
    4'b 0001, // index[ 8] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO03_MUX_SEL
    4'b 0001, // index[ 9] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO04_CFG
    4'b 0001, // index[10] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO04_MUX_SEL
    4'b 0001, // index[11] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO05_CFG
    4'b 0001, // index[12] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO05_MUX_SEL
    4'b 0001, // index[13] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO06_CFG
    4'b 0001, // index[14] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO06_MUX_SEL
    4'b 0001, // index[15] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO07_CFG
    4'b 0001, // index[16] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO07_MUX_SEL
    4'b 0001, // index[17] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO08_CFG
    4'b 0001, // index[18] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO08_MUX_SEL
    4'b 0001, // index[19] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO09_CFG
    4'b 0001, // index[20] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO09_MUX_SEL
    4'b 0001, // index[21] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO10_CFG
    4'b 0001, // index[22] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO10_MUX_SEL
    4'b 0001, // index[23] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO11_CFG
    4'b 0001, // index[24] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO11_MUX_SEL
    4'b 0001, // index[25] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO12_CFG
    4'b 0001, // index[26] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO12_MUX_SEL
    4'b 0001, // index[27] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO13_CFG
    4'b 0001, // index[28] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO13_MUX_SEL
    4'b 0001, // index[29] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO14_CFG
    4'b 0001, // index[30] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO14_MUX_SEL
    4'b 0001, // index[31] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO15_CFG
    4'b 0001, // index[32] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO15_MUX_SEL
    4'b 0001, // index[33] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO16_CFG
    4'b 0001, // index[34] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO16_MUX_SEL
    4'b 0001, // index[35] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO17_CFG
    4'b 0001, // index[36] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO17_MUX_SEL
    4'b 0001, // index[37] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO18_CFG
    4'b 0001, // index[38] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO18_MUX_SEL
    4'b 0001, // index[39] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO19_CFG
    4'b 0001, // index[40] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO19_MUX_SEL
    4'b 0001, // index[41] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO20_CFG
    4'b 0001, // index[42] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO20_MUX_SEL
    4'b 0001, // index[43] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO21_CFG
    4'b 0001, // index[44] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO21_MUX_SEL
    4'b 0001, // index[45] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO22_CFG
    4'b 0001, // index[46] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO22_MUX_SEL
    4'b 0001, // index[47] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO23_CFG
    4'b 0001, // index[48] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO23_MUX_SEL
    4'b 0001, // index[49] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO24_CFG
    4'b 0001, // index[50] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO24_MUX_SEL
    4'b 0001, // index[51] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO25_CFG
    4'b 0001, // index[52] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO25_MUX_SEL
    4'b 0001, // index[53] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO26_CFG
    4'b 0001, // index[54] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO26_MUX_SEL
    4'b 0001, // index[55] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO27_CFG
    4'b 0001, // index[56] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO27_MUX_SEL
    4'b 0001, // index[57] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO28_CFG
    4'b 0001, // index[58] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO28_MUX_SEL
    4'b 0001, // index[59] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO29_CFG
    4'b 0001, // index[60] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO29_MUX_SEL
    4'b 0001, // index[61] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO30_CFG
    4'b 0001, // index[62] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO30_MUX_SEL
    4'b 0001, // index[63] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO31_CFG
    4'b 0001  // index[64] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO31_MUX_SEL
  };

endpackage

