#!/bin/bash -e

# This is the script you use when you do a local test
# getting tests
git clone git@iis-git.ee.ethz.ch:pulp-tests/ml_tests.git \
    tests/ml_tests
git clone git@iis-git.ee.ethz.ch:pulp-sw/pulp_tests.git \
    tests/pulp_tests
git clone git@iis-git.ee.ethz.ch:pulp-tests/rt-tests.git \
    tests/rt-tests
git clone git@iis-git.ee.ethz.ch:pulp-sw/parallel_bare_tests.git \
    tests/parallel_bare_tests
git clone git@iis-git.ee.ethz.ch:pulp-sw/riscv_tests.git \
    tests/riscv_tests
git clone git@iis-git.ee.ethz.ch:pulp-sw/sequential_bare_tests.git \
    tests/sequential_bare_tests

# using "stable" versions
echo "Using stable versions of tests"
git -C tests/ml_tests checkout -q 9c49595a3dd9a0a2a776518b7de6c2cda903142b
git -C tests/pulp_tests checkout -q ce367a85b9d4b15e92b57cdfa7b715ecf6a92a45
git -C tests/rt-tests checkout -q f6bfda35cdbd363a94e7c8957fa7efc27093b106
git -C tests/parallel_bare_tests checkout -q 91b1bad09d088df9140f5391a87df3f6ebfab344
git -C tests/riscv_tests checkout -q 2ce43f33cc6f983e4deb3f79dec9663e02c10af5
git -C tests/sequential_bare_tests checkout -q f2cf176414a779b7fae31836d137cfaf6e78b719
