onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -group axi_xbar /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/clk_i
add wave -noupdate -group axi_xbar /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/rst_ni
add wave -noupdate -group axi_xbar /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/test_i
add wave -noupdate -group axi_xbar /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/addr_map_i
add wave -noupdate -group axi_xbar /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/en_default_mst_port_i
add wave -noupdate -group axi_xbar /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/default_mst_port_i
add wave -noupdate -group axi_xbar /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_reqs
add wave -noupdate -group axi_xbar /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_resps
add wave -noupdate -group axi_xbar /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_reqs
add wave -noupdate -group axi_xbar /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_resps
add wave -noupdate -group axi_xbar -group slv_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[0]/aw_id}
add wave -noupdate -group axi_xbar -group slv_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[0]/aw_addr}
add wave -noupdate -group axi_xbar -group slv_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[0]/aw_len}
add wave -noupdate -group axi_xbar -group slv_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[0]/aw_size}
add wave -noupdate -group axi_xbar -group slv_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[0]/aw_burst}
add wave -noupdate -group axi_xbar -group slv_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[0]/aw_lock}
add wave -noupdate -group axi_xbar -group slv_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[0]/aw_cache}
add wave -noupdate -group axi_xbar -group slv_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[0]/aw_prot}
add wave -noupdate -group axi_xbar -group slv_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[0]/aw_qos}
add wave -noupdate -group axi_xbar -group slv_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[0]/aw_region}
add wave -noupdate -group axi_xbar -group slv_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[0]/aw_atop}
add wave -noupdate -group axi_xbar -group slv_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[0]/aw_user}
add wave -noupdate -group axi_xbar -group slv_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[0]/aw_valid}
add wave -noupdate -group axi_xbar -group slv_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[0]/aw_ready}
add wave -noupdate -group axi_xbar -group slv_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[0]/w_data}
add wave -noupdate -group axi_xbar -group slv_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[0]/w_strb}
add wave -noupdate -group axi_xbar -group slv_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[0]/w_last}
add wave -noupdate -group axi_xbar -group slv_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[0]/w_user}
add wave -noupdate -group axi_xbar -group slv_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[0]/w_valid}
add wave -noupdate -group axi_xbar -group slv_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[0]/w_ready}
add wave -noupdate -group axi_xbar -group slv_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[0]/b_id}
add wave -noupdate -group axi_xbar -group slv_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[0]/b_resp}
add wave -noupdate -group axi_xbar -group slv_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[0]/b_user}
add wave -noupdate -group axi_xbar -group slv_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[0]/b_valid}
add wave -noupdate -group axi_xbar -group slv_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[0]/b_ready}
add wave -noupdate -group axi_xbar -group slv_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[0]/ar_id}
add wave -noupdate -group axi_xbar -group slv_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[0]/ar_addr}
add wave -noupdate -group axi_xbar -group slv_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[0]/ar_len}
add wave -noupdate -group axi_xbar -group slv_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[0]/ar_size}
add wave -noupdate -group axi_xbar -group slv_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[0]/ar_burst}
add wave -noupdate -group axi_xbar -group slv_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[0]/ar_lock}
add wave -noupdate -group axi_xbar -group slv_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[0]/ar_cache}
add wave -noupdate -group axi_xbar -group slv_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[0]/ar_prot}
add wave -noupdate -group axi_xbar -group slv_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[0]/ar_qos}
add wave -noupdate -group axi_xbar -group slv_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[0]/ar_region}
add wave -noupdate -group axi_xbar -group slv_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[0]/ar_user}
add wave -noupdate -group axi_xbar -group slv_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[0]/ar_valid}
add wave -noupdate -group axi_xbar -group slv_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[0]/ar_ready}
add wave -noupdate -group axi_xbar -group slv_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[0]/r_id}
add wave -noupdate -group axi_xbar -group slv_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[0]/r_data}
add wave -noupdate -group axi_xbar -group slv_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[0]/r_resp}
add wave -noupdate -group axi_xbar -group slv_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[0]/r_last}
add wave -noupdate -group axi_xbar -group slv_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[0]/r_user}
add wave -noupdate -group axi_xbar -group slv_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[0]/r_valid}
add wave -noupdate -group axi_xbar -group slv_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[0]/r_ready}
add wave -noupdate -group axi_xbar -group slv_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[1]/aw_id}
add wave -noupdate -group axi_xbar -group slv_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[1]/aw_addr}
add wave -noupdate -group axi_xbar -group slv_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[1]/aw_len}
add wave -noupdate -group axi_xbar -group slv_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[1]/aw_size}
add wave -noupdate -group axi_xbar -group slv_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[1]/aw_burst}
add wave -noupdate -group axi_xbar -group slv_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[1]/aw_lock}
add wave -noupdate -group axi_xbar -group slv_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[1]/aw_cache}
add wave -noupdate -group axi_xbar -group slv_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[1]/aw_prot}
add wave -noupdate -group axi_xbar -group slv_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[1]/aw_qos}
add wave -noupdate -group axi_xbar -group slv_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[1]/aw_region}
add wave -noupdate -group axi_xbar -group slv_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[1]/aw_atop}
add wave -noupdate -group axi_xbar -group slv_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[1]/aw_user}
add wave -noupdate -group axi_xbar -group slv_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[1]/aw_valid}
add wave -noupdate -group axi_xbar -group slv_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[1]/aw_ready}
add wave -noupdate -group axi_xbar -group slv_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[1]/w_data}
add wave -noupdate -group axi_xbar -group slv_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[1]/w_strb}
add wave -noupdate -group axi_xbar -group slv_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[1]/w_last}
add wave -noupdate -group axi_xbar -group slv_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[1]/w_user}
add wave -noupdate -group axi_xbar -group slv_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[1]/w_valid}
add wave -noupdate -group axi_xbar -group slv_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[1]/w_ready}
add wave -noupdate -group axi_xbar -group slv_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[1]/b_id}
add wave -noupdate -group axi_xbar -group slv_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[1]/b_resp}
add wave -noupdate -group axi_xbar -group slv_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[1]/b_user}
add wave -noupdate -group axi_xbar -group slv_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[1]/b_valid}
add wave -noupdate -group axi_xbar -group slv_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[1]/b_ready}
add wave -noupdate -group axi_xbar -group slv_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[1]/ar_id}
add wave -noupdate -group axi_xbar -group slv_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[1]/ar_addr}
add wave -noupdate -group axi_xbar -group slv_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[1]/ar_len}
add wave -noupdate -group axi_xbar -group slv_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[1]/ar_size}
add wave -noupdate -group axi_xbar -group slv_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[1]/ar_burst}
add wave -noupdate -group axi_xbar -group slv_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[1]/ar_lock}
add wave -noupdate -group axi_xbar -group slv_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[1]/ar_cache}
add wave -noupdate -group axi_xbar -group slv_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[1]/ar_prot}
add wave -noupdate -group axi_xbar -group slv_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[1]/ar_qos}
add wave -noupdate -group axi_xbar -group slv_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[1]/ar_region}
add wave -noupdate -group axi_xbar -group slv_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[1]/ar_user}
add wave -noupdate -group axi_xbar -group slv_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[1]/ar_valid}
add wave -noupdate -group axi_xbar -group slv_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[1]/ar_ready}
add wave -noupdate -group axi_xbar -group slv_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[1]/r_id}
add wave -noupdate -group axi_xbar -group slv_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[1]/r_data}
add wave -noupdate -group axi_xbar -group slv_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[1]/r_resp}
add wave -noupdate -group axi_xbar -group slv_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[1]/r_last}
add wave -noupdate -group axi_xbar -group slv_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[1]/r_user}
add wave -noupdate -group axi_xbar -group slv_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[1]/r_valid}
add wave -noupdate -group axi_xbar -group slv_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[1]/r_ready}
add wave -noupdate -group axi_xbar -group slv_port2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[2]/aw_id}
add wave -noupdate -group axi_xbar -group slv_port2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[2]/aw_addr}
add wave -noupdate -group axi_xbar -group slv_port2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[2]/aw_len}
add wave -noupdate -group axi_xbar -group slv_port2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[2]/aw_size}
add wave -noupdate -group axi_xbar -group slv_port2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[2]/aw_burst}
add wave -noupdate -group axi_xbar -group slv_port2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[2]/aw_lock}
add wave -noupdate -group axi_xbar -group slv_port2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[2]/aw_cache}
add wave -noupdate -group axi_xbar -group slv_port2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[2]/aw_prot}
add wave -noupdate -group axi_xbar -group slv_port2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[2]/aw_qos}
add wave -noupdate -group axi_xbar -group slv_port2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[2]/aw_region}
add wave -noupdate -group axi_xbar -group slv_port2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[2]/aw_atop}
add wave -noupdate -group axi_xbar -group slv_port2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[2]/aw_user}
add wave -noupdate -group axi_xbar -group slv_port2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[2]/aw_valid}
add wave -noupdate -group axi_xbar -group slv_port2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[2]/aw_ready}
add wave -noupdate -group axi_xbar -group slv_port2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[2]/w_data}
add wave -noupdate -group axi_xbar -group slv_port2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[2]/w_strb}
add wave -noupdate -group axi_xbar -group slv_port2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[2]/w_last}
add wave -noupdate -group axi_xbar -group slv_port2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[2]/w_user}
add wave -noupdate -group axi_xbar -group slv_port2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[2]/w_valid}
add wave -noupdate -group axi_xbar -group slv_port2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[2]/w_ready}
add wave -noupdate -group axi_xbar -group slv_port2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[2]/b_id}
add wave -noupdate -group axi_xbar -group slv_port2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[2]/b_resp}
add wave -noupdate -group axi_xbar -group slv_port2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[2]/b_user}
add wave -noupdate -group axi_xbar -group slv_port2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[2]/b_valid}
add wave -noupdate -group axi_xbar -group slv_port2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[2]/b_ready}
add wave -noupdate -group axi_xbar -group slv_port2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[2]/ar_id}
add wave -noupdate -group axi_xbar -group slv_port2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[2]/ar_addr}
add wave -noupdate -group axi_xbar -group slv_port2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[2]/ar_len}
add wave -noupdate -group axi_xbar -group slv_port2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[2]/ar_size}
add wave -noupdate -group axi_xbar -group slv_port2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[2]/ar_burst}
add wave -noupdate -group axi_xbar -group slv_port2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[2]/ar_lock}
add wave -noupdate -group axi_xbar -group slv_port2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[2]/ar_cache}
add wave -noupdate -group axi_xbar -group slv_port2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[2]/ar_prot}
add wave -noupdate -group axi_xbar -group slv_port2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[2]/ar_qos}
add wave -noupdate -group axi_xbar -group slv_port2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[2]/ar_region}
add wave -noupdate -group axi_xbar -group slv_port2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[2]/ar_user}
add wave -noupdate -group axi_xbar -group slv_port2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[2]/ar_valid}
add wave -noupdate -group axi_xbar -group slv_port2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[2]/ar_ready}
add wave -noupdate -group axi_xbar -group slv_port2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[2]/r_id}
add wave -noupdate -group axi_xbar -group slv_port2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[2]/r_data}
add wave -noupdate -group axi_xbar -group slv_port2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[2]/r_resp}
add wave -noupdate -group axi_xbar -group slv_port2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[2]/r_last}
add wave -noupdate -group axi_xbar -group slv_port2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[2]/r_user}
add wave -noupdate -group axi_xbar -group slv_port2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[2]/r_valid}
add wave -noupdate -group axi_xbar -group slv_port2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[2]/r_ready}
add wave -noupdate -group axi_xbar -group slv_port3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[3]/aw_id}
add wave -noupdate -group axi_xbar -group slv_port3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[3]/aw_addr}
add wave -noupdate -group axi_xbar -group slv_port3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[3]/aw_len}
add wave -noupdate -group axi_xbar -group slv_port3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[3]/aw_size}
add wave -noupdate -group axi_xbar -group slv_port3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[3]/aw_burst}
add wave -noupdate -group axi_xbar -group slv_port3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[3]/aw_lock}
add wave -noupdate -group axi_xbar -group slv_port3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[3]/aw_cache}
add wave -noupdate -group axi_xbar -group slv_port3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[3]/aw_prot}
add wave -noupdate -group axi_xbar -group slv_port3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[3]/aw_qos}
add wave -noupdate -group axi_xbar -group slv_port3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[3]/aw_region}
add wave -noupdate -group axi_xbar -group slv_port3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[3]/aw_atop}
add wave -noupdate -group axi_xbar -group slv_port3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[3]/aw_user}
add wave -noupdate -group axi_xbar -group slv_port3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[3]/aw_valid}
add wave -noupdate -group axi_xbar -group slv_port3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[3]/aw_ready}
add wave -noupdate -group axi_xbar -group slv_port3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[3]/w_data}
add wave -noupdate -group axi_xbar -group slv_port3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[3]/w_strb}
add wave -noupdate -group axi_xbar -group slv_port3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[3]/w_last}
add wave -noupdate -group axi_xbar -group slv_port3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[3]/w_user}
add wave -noupdate -group axi_xbar -group slv_port3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[3]/w_valid}
add wave -noupdate -group axi_xbar -group slv_port3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[3]/w_ready}
add wave -noupdate -group axi_xbar -group slv_port3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[3]/b_id}
add wave -noupdate -group axi_xbar -group slv_port3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[3]/b_resp}
add wave -noupdate -group axi_xbar -group slv_port3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[3]/b_user}
add wave -noupdate -group axi_xbar -group slv_port3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[3]/b_valid}
add wave -noupdate -group axi_xbar -group slv_port3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[3]/b_ready}
add wave -noupdate -group axi_xbar -group slv_port3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[3]/ar_id}
add wave -noupdate -group axi_xbar -group slv_port3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[3]/ar_addr}
add wave -noupdate -group axi_xbar -group slv_port3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[3]/ar_len}
add wave -noupdate -group axi_xbar -group slv_port3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[3]/ar_size}
add wave -noupdate -group axi_xbar -group slv_port3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[3]/ar_burst}
add wave -noupdate -group axi_xbar -group slv_port3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[3]/ar_lock}
add wave -noupdate -group axi_xbar -group slv_port3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[3]/ar_cache}
add wave -noupdate -group axi_xbar -group slv_port3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[3]/ar_prot}
add wave -noupdate -group axi_xbar -group slv_port3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[3]/ar_qos}
add wave -noupdate -group axi_xbar -group slv_port3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[3]/ar_region}
add wave -noupdate -group axi_xbar -group slv_port3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[3]/ar_user}
add wave -noupdate -group axi_xbar -group slv_port3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[3]/ar_valid}
add wave -noupdate -group axi_xbar -group slv_port3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[3]/ar_ready}
add wave -noupdate -group axi_xbar -group slv_port3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[3]/r_id}
add wave -noupdate -group axi_xbar -group slv_port3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[3]/r_data}
add wave -noupdate -group axi_xbar -group slv_port3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[3]/r_resp}
add wave -noupdate -group axi_xbar -group slv_port3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[3]/r_last}
add wave -noupdate -group axi_xbar -group slv_port3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[3]/r_user}
add wave -noupdate -group axi_xbar -group slv_port3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[3]/r_valid}
add wave -noupdate -group axi_xbar -group slv_port3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[3]/r_ready}
add wave -noupdate -group axi_xbar -group slv_port4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[4]/aw_id}
add wave -noupdate -group axi_xbar -group slv_port4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[4]/aw_addr}
add wave -noupdate -group axi_xbar -group slv_port4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[4]/aw_len}
add wave -noupdate -group axi_xbar -group slv_port4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[4]/aw_size}
add wave -noupdate -group axi_xbar -group slv_port4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[4]/aw_burst}
add wave -noupdate -group axi_xbar -group slv_port4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[4]/aw_lock}
add wave -noupdate -group axi_xbar -group slv_port4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[4]/aw_cache}
add wave -noupdate -group axi_xbar -group slv_port4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[4]/aw_prot}
add wave -noupdate -group axi_xbar -group slv_port4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[4]/aw_qos}
add wave -noupdate -group axi_xbar -group slv_port4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[4]/aw_region}
add wave -noupdate -group axi_xbar -group slv_port4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[4]/aw_atop}
add wave -noupdate -group axi_xbar -group slv_port4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[4]/aw_user}
add wave -noupdate -group axi_xbar -group slv_port4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[4]/aw_valid}
add wave -noupdate -group axi_xbar -group slv_port4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[4]/aw_ready}
add wave -noupdate -group axi_xbar -group slv_port4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[4]/w_data}
add wave -noupdate -group axi_xbar -group slv_port4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[4]/w_strb}
add wave -noupdate -group axi_xbar -group slv_port4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[4]/w_last}
add wave -noupdate -group axi_xbar -group slv_port4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[4]/w_user}
add wave -noupdate -group axi_xbar -group slv_port4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[4]/w_valid}
add wave -noupdate -group axi_xbar -group slv_port4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[4]/w_ready}
add wave -noupdate -group axi_xbar -group slv_port4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[4]/b_id}
add wave -noupdate -group axi_xbar -group slv_port4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[4]/b_resp}
add wave -noupdate -group axi_xbar -group slv_port4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[4]/b_user}
add wave -noupdate -group axi_xbar -group slv_port4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[4]/b_valid}
add wave -noupdate -group axi_xbar -group slv_port4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[4]/b_ready}
add wave -noupdate -group axi_xbar -group slv_port4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[4]/ar_id}
add wave -noupdate -group axi_xbar -group slv_port4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[4]/ar_addr}
add wave -noupdate -group axi_xbar -group slv_port4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[4]/ar_len}
add wave -noupdate -group axi_xbar -group slv_port4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[4]/ar_size}
add wave -noupdate -group axi_xbar -group slv_port4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[4]/ar_burst}
add wave -noupdate -group axi_xbar -group slv_port4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[4]/ar_lock}
add wave -noupdate -group axi_xbar -group slv_port4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[4]/ar_cache}
add wave -noupdate -group axi_xbar -group slv_port4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[4]/ar_prot}
add wave -noupdate -group axi_xbar -group slv_port4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[4]/ar_qos}
add wave -noupdate -group axi_xbar -group slv_port4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[4]/ar_region}
add wave -noupdate -group axi_xbar -group slv_port4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[4]/ar_user}
add wave -noupdate -group axi_xbar -group slv_port4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[4]/ar_valid}
add wave -noupdate -group axi_xbar -group slv_port4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[4]/ar_ready}
add wave -noupdate -group axi_xbar -group slv_port4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[4]/r_id}
add wave -noupdate -group axi_xbar -group slv_port4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[4]/r_data}
add wave -noupdate -group axi_xbar -group slv_port4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[4]/r_resp}
add wave -noupdate -group axi_xbar -group slv_port4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[4]/r_last}
add wave -noupdate -group axi_xbar -group slv_port4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[4]/r_user}
add wave -noupdate -group axi_xbar -group slv_port4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[4]/r_valid}
add wave -noupdate -group axi_xbar -group slv_port4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/slv_ports[4]/r_ready}
add wave -noupdate -group axi_xbar -group mst_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[0]/aw_id}
add wave -noupdate -group axi_xbar -group mst_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[0]/aw_addr}
add wave -noupdate -group axi_xbar -group mst_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[0]/aw_len}
add wave -noupdate -group axi_xbar -group mst_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[0]/aw_size}
add wave -noupdate -group axi_xbar -group mst_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[0]/aw_burst}
add wave -noupdate -group axi_xbar -group mst_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[0]/aw_lock}
add wave -noupdate -group axi_xbar -group mst_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[0]/aw_cache}
add wave -noupdate -group axi_xbar -group mst_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[0]/aw_prot}
add wave -noupdate -group axi_xbar -group mst_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[0]/aw_qos}
add wave -noupdate -group axi_xbar -group mst_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[0]/aw_region}
add wave -noupdate -group axi_xbar -group mst_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[0]/aw_atop}
add wave -noupdate -group axi_xbar -group mst_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[0]/aw_user}
add wave -noupdate -group axi_xbar -group mst_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[0]/aw_valid}
add wave -noupdate -group axi_xbar -group mst_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[0]/aw_ready}
add wave -noupdate -group axi_xbar -group mst_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[0]/w_data}
add wave -noupdate -group axi_xbar -group mst_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[0]/w_strb}
add wave -noupdate -group axi_xbar -group mst_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[0]/w_last}
add wave -noupdate -group axi_xbar -group mst_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[0]/w_user}
add wave -noupdate -group axi_xbar -group mst_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[0]/w_valid}
add wave -noupdate -group axi_xbar -group mst_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[0]/w_ready}
add wave -noupdate -group axi_xbar -group mst_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[0]/b_id}
add wave -noupdate -group axi_xbar -group mst_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[0]/b_resp}
add wave -noupdate -group axi_xbar -group mst_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[0]/b_user}
add wave -noupdate -group axi_xbar -group mst_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[0]/b_valid}
add wave -noupdate -group axi_xbar -group mst_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[0]/b_ready}
add wave -noupdate -group axi_xbar -group mst_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[0]/ar_id}
add wave -noupdate -group axi_xbar -group mst_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[0]/ar_addr}
add wave -noupdate -group axi_xbar -group mst_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[0]/ar_len}
add wave -noupdate -group axi_xbar -group mst_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[0]/ar_size}
add wave -noupdate -group axi_xbar -group mst_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[0]/ar_burst}
add wave -noupdate -group axi_xbar -group mst_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[0]/ar_lock}
add wave -noupdate -group axi_xbar -group mst_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[0]/ar_cache}
add wave -noupdate -group axi_xbar -group mst_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[0]/ar_prot}
add wave -noupdate -group axi_xbar -group mst_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[0]/ar_qos}
add wave -noupdate -group axi_xbar -group mst_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[0]/ar_region}
add wave -noupdate -group axi_xbar -group mst_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[0]/ar_user}
add wave -noupdate -group axi_xbar -group mst_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[0]/ar_valid}
add wave -noupdate -group axi_xbar -group mst_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[0]/ar_ready}
add wave -noupdate -group axi_xbar -group mst_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[0]/r_id}
add wave -noupdate -group axi_xbar -group mst_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[0]/r_data}
add wave -noupdate -group axi_xbar -group mst_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[0]/r_resp}
add wave -noupdate -group axi_xbar -group mst_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[0]/r_last}
add wave -noupdate -group axi_xbar -group mst_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[0]/r_user}
add wave -noupdate -group axi_xbar -group mst_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[0]/r_valid}
add wave -noupdate -group axi_xbar -group mst_port0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[0]/r_ready}
add wave -noupdate -group axi_xbar -group mst_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[1]/aw_id}
add wave -noupdate -group axi_xbar -group mst_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[1]/aw_addr}
add wave -noupdate -group axi_xbar -group mst_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[1]/aw_len}
add wave -noupdate -group axi_xbar -group mst_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[1]/aw_size}
add wave -noupdate -group axi_xbar -group mst_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[1]/aw_burst}
add wave -noupdate -group axi_xbar -group mst_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[1]/aw_lock}
add wave -noupdate -group axi_xbar -group mst_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[1]/aw_cache}
add wave -noupdate -group axi_xbar -group mst_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[1]/aw_prot}
add wave -noupdate -group axi_xbar -group mst_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[1]/aw_qos}
add wave -noupdate -group axi_xbar -group mst_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[1]/aw_region}
add wave -noupdate -group axi_xbar -group mst_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[1]/aw_atop}
add wave -noupdate -group axi_xbar -group mst_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[1]/aw_user}
add wave -noupdate -group axi_xbar -group mst_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[1]/aw_valid}
add wave -noupdate -group axi_xbar -group mst_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[1]/aw_ready}
add wave -noupdate -group axi_xbar -group mst_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[1]/w_data}
add wave -noupdate -group axi_xbar -group mst_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[1]/w_strb}
add wave -noupdate -group axi_xbar -group mst_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[1]/w_last}
add wave -noupdate -group axi_xbar -group mst_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[1]/w_user}
add wave -noupdate -group axi_xbar -group mst_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[1]/w_valid}
add wave -noupdate -group axi_xbar -group mst_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[1]/w_ready}
add wave -noupdate -group axi_xbar -group mst_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[1]/b_id}
add wave -noupdate -group axi_xbar -group mst_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[1]/b_resp}
add wave -noupdate -group axi_xbar -group mst_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[1]/b_user}
add wave -noupdate -group axi_xbar -group mst_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[1]/b_valid}
add wave -noupdate -group axi_xbar -group mst_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[1]/b_ready}
add wave -noupdate -group axi_xbar -group mst_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[1]/ar_id}
add wave -noupdate -group axi_xbar -group mst_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[1]/ar_addr}
add wave -noupdate -group axi_xbar -group mst_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[1]/ar_len}
add wave -noupdate -group axi_xbar -group mst_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[1]/ar_size}
add wave -noupdate -group axi_xbar -group mst_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[1]/ar_burst}
add wave -noupdate -group axi_xbar -group mst_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[1]/ar_lock}
add wave -noupdate -group axi_xbar -group mst_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[1]/ar_cache}
add wave -noupdate -group axi_xbar -group mst_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[1]/ar_prot}
add wave -noupdate -group axi_xbar -group mst_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[1]/ar_qos}
add wave -noupdate -group axi_xbar -group mst_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[1]/ar_region}
add wave -noupdate -group axi_xbar -group mst_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[1]/ar_user}
add wave -noupdate -group axi_xbar -group mst_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[1]/ar_valid}
add wave -noupdate -group axi_xbar -group mst_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[1]/ar_ready}
add wave -noupdate -group axi_xbar -group mst_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[1]/r_id}
add wave -noupdate -group axi_xbar -group mst_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[1]/r_data}
add wave -noupdate -group axi_xbar -group mst_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[1]/r_resp}
add wave -noupdate -group axi_xbar -group mst_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[1]/r_last}
add wave -noupdate -group axi_xbar -group mst_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[1]/r_user}
add wave -noupdate -group axi_xbar -group mst_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[1]/r_valid}
add wave -noupdate -group axi_xbar -group mst_port1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/i_axi_xbar/mst_ports[1]/r_ready}
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {5873214196 ps} 0} {{Cursor 2} {52985734 ps} 1} {{Cursor 12} {195902077 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 250
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ps} {6167157150 ps}
