onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -group soc_interconnect /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/clk_i
add wave -noupdate -group soc_interconnect /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/rst_ni
add wave -noupdate -group soc_interconnect /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/test_en_i
add wave -noupdate -group soc_interconnect /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/addr_space_l2_demux
add wave -noupdate -group soc_interconnect /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/addr_space_contiguous
add wave -noupdate -group soc_interconnect /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/addr_space_axi
add wave -noupdate -group soc_interconnect /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/error_valid_d
add wave -noupdate -group soc_interconnect /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/error_valid_q
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[0]/aw_id}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[0]/aw_addr}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[0]/aw_len}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[0]/aw_size}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[0]/aw_burst}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[0]/aw_lock}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[0]/aw_cache}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[0]/aw_prot}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[0]/aw_qos}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[0]/aw_region}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[0]/aw_atop}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[0]/aw_user}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[0]/aw_valid}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[0]/aw_ready}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[0]/w_data}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[0]/w_strb}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[0]/w_last}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[0]/w_user}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[0]/w_valid}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[0]/w_ready}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[0]/b_id}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[0]/b_resp}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[0]/b_user}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[0]/b_valid}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[0]/b_ready}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[0]/ar_id}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[0]/ar_addr}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[0]/ar_len}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[0]/ar_size}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[0]/ar_burst}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[0]/ar_lock}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[0]/ar_cache}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[0]/ar_prot}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[0]/ar_qos}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[0]/ar_region}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[0]/ar_user}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[0]/ar_valid}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[0]/ar_ready}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[0]/r_id}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[0]/r_data}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[0]/r_resp}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[0]/r_last}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[0]/r_user}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[0]/r_valid}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[0]/r_ready}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[1]/aw_id}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[1]/aw_addr}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[1]/aw_len}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[1]/aw_size}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[1]/aw_burst}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[1]/aw_lock}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[1]/aw_cache}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[1]/aw_prot}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[1]/aw_qos}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[1]/aw_region}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[1]/aw_atop}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[1]/aw_user}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[1]/aw_valid}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[1]/aw_ready}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[1]/w_data}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[1]/w_strb}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[1]/w_last}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[1]/w_user}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[1]/w_valid}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[1]/w_ready}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[1]/b_id}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[1]/b_resp}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[1]/b_user}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[1]/b_valid}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[1]/b_ready}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[1]/ar_id}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[1]/ar_addr}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[1]/ar_len}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[1]/ar_size}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[1]/ar_burst}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[1]/ar_lock}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[1]/ar_cache}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[1]/ar_prot}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[1]/ar_qos}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[1]/ar_region}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[1]/ar_user}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[1]/ar_valid}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[1]/ar_ready}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[1]/r_id}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[1]/r_data}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[1]/r_resp}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[1]/r_last}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[1]/r_user}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[1]/r_valid}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[1]/r_ready}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[2]/aw_id}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[2]/aw_addr}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[2]/aw_len}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[2]/aw_size}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[2]/aw_burst}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[2]/aw_lock}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[2]/aw_cache}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[2]/aw_prot}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[2]/aw_qos}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[2]/aw_region}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[2]/aw_atop}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[2]/aw_user}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[2]/aw_valid}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[2]/aw_ready}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[2]/w_data}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[2]/w_strb}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[2]/w_last}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[2]/w_user}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[2]/w_valid}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[2]/w_ready}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[2]/b_id}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[2]/b_resp}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[2]/b_user}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[2]/b_valid}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[2]/b_ready}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[2]/ar_id}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[2]/ar_addr}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[2]/ar_len}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[2]/ar_size}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[2]/ar_burst}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[2]/ar_lock}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[2]/ar_cache}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[2]/ar_prot}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[2]/ar_qos}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[2]/ar_region}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[2]/ar_user}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[2]/ar_valid}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[2]/ar_ready}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[2]/r_id}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[2]/r_data}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[2]/r_resp}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[2]/r_last}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[2]/r_user}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[2]/r_valid}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[2]/r_ready}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[3]/aw_id}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[3]/aw_addr}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[3]/aw_len}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[3]/aw_size}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[3]/aw_burst}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[3]/aw_lock}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[3]/aw_cache}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[3]/aw_prot}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[3]/aw_qos}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[3]/aw_region}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[3]/aw_atop}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[3]/aw_user}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[3]/aw_valid}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[3]/aw_ready}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[3]/w_data}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[3]/w_strb}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[3]/w_last}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[3]/w_user}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[3]/w_valid}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[3]/w_ready}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[3]/b_id}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[3]/b_resp}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[3]/b_user}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[3]/b_valid}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[3]/b_ready}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[3]/ar_id}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[3]/ar_addr}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[3]/ar_len}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[3]/ar_size}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[3]/ar_burst}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[3]/ar_lock}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[3]/ar_cache}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[3]/ar_prot}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[3]/ar_qos}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[3]/ar_region}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[3]/ar_user}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[3]/ar_valid}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[3]/ar_ready}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[3]/r_id}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[3]/r_data}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[3]/r_resp}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[3]/r_last}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[3]/r_user}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[3]/r_valid}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[3]/r_ready}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[4]/aw_id}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[4]/aw_addr}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[4]/aw_len}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[4]/aw_size}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[4]/aw_burst}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[4]/aw_lock}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[4]/aw_cache}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[4]/aw_prot}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[4]/aw_qos}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[4]/aw_region}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[4]/aw_atop}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[4]/aw_user}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[4]/aw_valid}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[4]/aw_ready}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[4]/w_data}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[4]/w_strb}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[4]/w_last}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[4]/w_user}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[4]/w_valid}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[4]/w_ready}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[4]/b_id}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[4]/b_resp}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[4]/b_user}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[4]/b_valid}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[4]/b_ready}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[4]/ar_id}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[4]/ar_addr}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[4]/ar_len}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[4]/ar_size}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[4]/ar_burst}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[4]/ar_lock}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[4]/ar_cache}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[4]/ar_prot}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[4]/ar_qos}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[4]/ar_region}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[4]/ar_user}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[4]/ar_valid}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[4]/ar_ready}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[4]/r_id}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[4]/r_data}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[4]/r_resp}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[4]/r_last}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[4]/r_user}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[4]/r_valid}
add wave -noupdate -group soc_interconnect -group axi_bridge_2_axi_xbar4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_bridge_2_axi_xbar[4]/r_ready}
add wave -noupdate -group soc_interconnect -group axi_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[0]/aw_id}
add wave -noupdate -group soc_interconnect -group axi_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[0]/aw_addr}
add wave -noupdate -group soc_interconnect -group axi_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[0]/aw_len}
add wave -noupdate -group soc_interconnect -group axi_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[0]/aw_size}
add wave -noupdate -group soc_interconnect -group axi_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[0]/aw_burst}
add wave -noupdate -group soc_interconnect -group axi_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[0]/aw_lock}
add wave -noupdate -group soc_interconnect -group axi_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[0]/aw_cache}
add wave -noupdate -group soc_interconnect -group axi_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[0]/aw_prot}
add wave -noupdate -group soc_interconnect -group axi_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[0]/aw_qos}
add wave -noupdate -group soc_interconnect -group axi_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[0]/aw_region}
add wave -noupdate -group soc_interconnect -group axi_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[0]/aw_atop}
add wave -noupdate -group soc_interconnect -group axi_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[0]/aw_user}
add wave -noupdate -group soc_interconnect -group axi_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[0]/aw_valid}
add wave -noupdate -group soc_interconnect -group axi_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[0]/aw_ready}
add wave -noupdate -group soc_interconnect -group axi_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[0]/w_data}
add wave -noupdate -group soc_interconnect -group axi_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[0]/w_strb}
add wave -noupdate -group soc_interconnect -group axi_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[0]/w_last}
add wave -noupdate -group soc_interconnect -group axi_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[0]/w_user}
add wave -noupdate -group soc_interconnect -group axi_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[0]/w_valid}
add wave -noupdate -group soc_interconnect -group axi_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[0]/w_ready}
add wave -noupdate -group soc_interconnect -group axi_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[0]/b_id}
add wave -noupdate -group soc_interconnect -group axi_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[0]/b_resp}
add wave -noupdate -group soc_interconnect -group axi_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[0]/b_user}
add wave -noupdate -group soc_interconnect -group axi_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[0]/b_valid}
add wave -noupdate -group soc_interconnect -group axi_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[0]/b_ready}
add wave -noupdate -group soc_interconnect -group axi_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[0]/ar_id}
add wave -noupdate -group soc_interconnect -group axi_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[0]/ar_addr}
add wave -noupdate -group soc_interconnect -group axi_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[0]/ar_len}
add wave -noupdate -group soc_interconnect -group axi_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[0]/ar_size}
add wave -noupdate -group soc_interconnect -group axi_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[0]/ar_burst}
add wave -noupdate -group soc_interconnect -group axi_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[0]/ar_lock}
add wave -noupdate -group soc_interconnect -group axi_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[0]/ar_cache}
add wave -noupdate -group soc_interconnect -group axi_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[0]/ar_prot}
add wave -noupdate -group soc_interconnect -group axi_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[0]/ar_qos}
add wave -noupdate -group soc_interconnect -group axi_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[0]/ar_region}
add wave -noupdate -group soc_interconnect -group axi_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[0]/ar_user}
add wave -noupdate -group soc_interconnect -group axi_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[0]/ar_valid}
add wave -noupdate -group soc_interconnect -group axi_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[0]/ar_ready}
add wave -noupdate -group soc_interconnect -group axi_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[0]/r_id}
add wave -noupdate -group soc_interconnect -group axi_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[0]/r_data}
add wave -noupdate -group soc_interconnect -group axi_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[0]/r_resp}
add wave -noupdate -group soc_interconnect -group axi_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[0]/r_last}
add wave -noupdate -group soc_interconnect -group axi_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[0]/r_user}
add wave -noupdate -group soc_interconnect -group axi_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[0]/r_valid}
add wave -noupdate -group soc_interconnect -group axi_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[0]/r_ready}
add wave -noupdate -group soc_interconnect -group axi_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[1]/aw_id}
add wave -noupdate -group soc_interconnect -group axi_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[1]/aw_addr}
add wave -noupdate -group soc_interconnect -group axi_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[1]/aw_len}
add wave -noupdate -group soc_interconnect -group axi_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[1]/aw_size}
add wave -noupdate -group soc_interconnect -group axi_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[1]/aw_burst}
add wave -noupdate -group soc_interconnect -group axi_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[1]/aw_lock}
add wave -noupdate -group soc_interconnect -group axi_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[1]/aw_cache}
add wave -noupdate -group soc_interconnect -group axi_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[1]/aw_prot}
add wave -noupdate -group soc_interconnect -group axi_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[1]/aw_qos}
add wave -noupdate -group soc_interconnect -group axi_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[1]/aw_region}
add wave -noupdate -group soc_interconnect -group axi_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[1]/aw_atop}
add wave -noupdate -group soc_interconnect -group axi_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[1]/aw_user}
add wave -noupdate -group soc_interconnect -group axi_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[1]/aw_valid}
add wave -noupdate -group soc_interconnect -group axi_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[1]/aw_ready}
add wave -noupdate -group soc_interconnect -group axi_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[1]/w_data}
add wave -noupdate -group soc_interconnect -group axi_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[1]/w_strb}
add wave -noupdate -group soc_interconnect -group axi_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[1]/w_last}
add wave -noupdate -group soc_interconnect -group axi_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[1]/w_user}
add wave -noupdate -group soc_interconnect -group axi_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[1]/w_valid}
add wave -noupdate -group soc_interconnect -group axi_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[1]/w_ready}
add wave -noupdate -group soc_interconnect -group axi_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[1]/b_id}
add wave -noupdate -group soc_interconnect -group axi_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[1]/b_resp}
add wave -noupdate -group soc_interconnect -group axi_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[1]/b_user}
add wave -noupdate -group soc_interconnect -group axi_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[1]/b_valid}
add wave -noupdate -group soc_interconnect -group axi_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[1]/b_ready}
add wave -noupdate -group soc_interconnect -group axi_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[1]/ar_id}
add wave -noupdate -group soc_interconnect -group axi_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[1]/ar_addr}
add wave -noupdate -group soc_interconnect -group axi_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[1]/ar_len}
add wave -noupdate -group soc_interconnect -group axi_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[1]/ar_size}
add wave -noupdate -group soc_interconnect -group axi_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[1]/ar_burst}
add wave -noupdate -group soc_interconnect -group axi_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[1]/ar_lock}
add wave -noupdate -group soc_interconnect -group axi_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[1]/ar_cache}
add wave -noupdate -group soc_interconnect -group axi_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[1]/ar_prot}
add wave -noupdate -group soc_interconnect -group axi_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[1]/ar_qos}
add wave -noupdate -group soc_interconnect -group axi_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[1]/ar_region}
add wave -noupdate -group soc_interconnect -group axi_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[1]/ar_user}
add wave -noupdate -group soc_interconnect -group axi_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[1]/ar_valid}
add wave -noupdate -group soc_interconnect -group axi_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[1]/ar_ready}
add wave -noupdate -group soc_interconnect -group axi_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[1]/r_id}
add wave -noupdate -group soc_interconnect -group axi_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[1]/r_data}
add wave -noupdate -group soc_interconnect -group axi_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[1]/r_resp}
add wave -noupdate -group soc_interconnect -group axi_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[1]/r_last}
add wave -noupdate -group soc_interconnect -group axi_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[1]/r_user}
add wave -noupdate -group soc_interconnect -group axi_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[1]/r_valid}
add wave -noupdate -group soc_interconnect -group axi_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/axi_slaves[1]/r_ready}
add wave -noupdate -group soc_interconnect -group contiguous_slaves0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/contiguous_slaves[0]/req}
add wave -noupdate -group soc_interconnect -group contiguous_slaves0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/contiguous_slaves[0]/add}
add wave -noupdate -group soc_interconnect -group contiguous_slaves0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/contiguous_slaves[0]/wen}
add wave -noupdate -group soc_interconnect -group contiguous_slaves0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/contiguous_slaves[0]/wdata}
add wave -noupdate -group soc_interconnect -group contiguous_slaves0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/contiguous_slaves[0]/be}
add wave -noupdate -group soc_interconnect -group contiguous_slaves0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/contiguous_slaves[0]/gnt}
add wave -noupdate -group soc_interconnect -group contiguous_slaves0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/contiguous_slaves[0]/r_opc}
add wave -noupdate -group soc_interconnect -group contiguous_slaves0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/contiguous_slaves[0]/r_rdata}
add wave -noupdate -group soc_interconnect -group contiguous_slaves0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/contiguous_slaves[0]/r_valid}
add wave -noupdate -group soc_interconnect -group contiguous_slaves1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/contiguous_slaves[1]/req}
add wave -noupdate -group soc_interconnect -group contiguous_slaves1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/contiguous_slaves[1]/add}
add wave -noupdate -group soc_interconnect -group contiguous_slaves1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/contiguous_slaves[1]/wen}
add wave -noupdate -group soc_interconnect -group contiguous_slaves1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/contiguous_slaves[1]/wdata}
add wave -noupdate -group soc_interconnect -group contiguous_slaves1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/contiguous_slaves[1]/be}
add wave -noupdate -group soc_interconnect -group contiguous_slaves1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/contiguous_slaves[1]/gnt}
add wave -noupdate -group soc_interconnect -group contiguous_slaves1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/contiguous_slaves[1]/r_opc}
add wave -noupdate -group soc_interconnect -group contiguous_slaves1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/contiguous_slaves[1]/r_rdata}
add wave -noupdate -group soc_interconnect -group contiguous_slaves1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/contiguous_slaves[1]/r_valid}
add wave -noupdate -group soc_interconnect -group contiguous_slaves_2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/contiguous_slaves[2]/req}
add wave -noupdate -group soc_interconnect -group contiguous_slaves_2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/contiguous_slaves[2]/add}
add wave -noupdate -group soc_interconnect -group contiguous_slaves_2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/contiguous_slaves[2]/wen}
add wave -noupdate -group soc_interconnect -group contiguous_slaves_2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/contiguous_slaves[2]/wdata}
add wave -noupdate -group soc_interconnect -group contiguous_slaves_2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/contiguous_slaves[2]/be}
add wave -noupdate -group soc_interconnect -group contiguous_slaves_2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/contiguous_slaves[2]/gnt}
add wave -noupdate -group soc_interconnect -group contiguous_slaves_2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/contiguous_slaves[2]/r_opc}
add wave -noupdate -group soc_interconnect -group contiguous_slaves_2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/contiguous_slaves[2]/r_rdata}
add wave -noupdate -group soc_interconnect -group contiguous_slaves_2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/contiguous_slaves[2]/r_valid}
add wave -noupdate -group soc_interconnect -group error_slave /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/error_slave/req
add wave -noupdate -group soc_interconnect -group error_slave /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/error_slave/add
add wave -noupdate -group soc_interconnect -group error_slave /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/error_slave/wen
add wave -noupdate -group soc_interconnect -group error_slave /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/error_slave/wdata
add wave -noupdate -group soc_interconnect -group error_slave /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/error_slave/be
add wave -noupdate -group soc_interconnect -group error_slave /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/error_slave/gnt
add wave -noupdate -group soc_interconnect -group error_slave /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/error_slave/r_opc
add wave -noupdate -group soc_interconnect -group error_slave /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/error_slave/r_rdata
add wave -noupdate -group soc_interconnect -group error_slave /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/error_slave/r_valid
add wave -noupdate -group soc_interconnect -group interleaved_masters0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[0]/req}
add wave -noupdate -group soc_interconnect -group interleaved_masters0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[0]/add}
add wave -noupdate -group soc_interconnect -group interleaved_masters0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[0]/wen}
add wave -noupdate -group soc_interconnect -group interleaved_masters0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[0]/wdata}
add wave -noupdate -group soc_interconnect -group interleaved_masters0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[0]/be}
add wave -noupdate -group soc_interconnect -group interleaved_masters0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[0]/gnt}
add wave -noupdate -group soc_interconnect -group interleaved_masters0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[0]/r_opc}
add wave -noupdate -group soc_interconnect -group interleaved_masters0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[0]/r_rdata}
add wave -noupdate -group soc_interconnect -group interleaved_masters0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[0]/r_valid}
add wave -noupdate -group soc_interconnect -group interleaved_masters1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[1]/req}
add wave -noupdate -group soc_interconnect -group interleaved_masters1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[1]/add}
add wave -noupdate -group soc_interconnect -group interleaved_masters1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[1]/wen}
add wave -noupdate -group soc_interconnect -group interleaved_masters1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[1]/wdata}
add wave -noupdate -group soc_interconnect -group interleaved_masters1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[1]/be}
add wave -noupdate -group soc_interconnect -group interleaved_masters1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[1]/gnt}
add wave -noupdate -group soc_interconnect -group interleaved_masters1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[1]/r_opc}
add wave -noupdate -group soc_interconnect -group interleaved_masters1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[1]/r_rdata}
add wave -noupdate -group soc_interconnect -group interleaved_masters1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[1]/r_valid}
add wave -noupdate -group soc_interconnect -group interleaved_masters2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[2]/req}
add wave -noupdate -group soc_interconnect -group interleaved_masters2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[2]/add}
add wave -noupdate -group soc_interconnect -group interleaved_masters2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[2]/wen}
add wave -noupdate -group soc_interconnect -group interleaved_masters2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[2]/wdata}
add wave -noupdate -group soc_interconnect -group interleaved_masters2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[2]/be}
add wave -noupdate -group soc_interconnect -group interleaved_masters2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[2]/gnt}
add wave -noupdate -group soc_interconnect -group interleaved_masters2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[2]/r_opc}
add wave -noupdate -group soc_interconnect -group interleaved_masters2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[2]/r_rdata}
add wave -noupdate -group soc_interconnect -group interleaved_masters2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[2]/r_valid}
add wave -noupdate -group soc_interconnect -group interleaved_masters3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[3]/req}
add wave -noupdate -group soc_interconnect -group interleaved_masters3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[3]/add}
add wave -noupdate -group soc_interconnect -group interleaved_masters3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[3]/wen}
add wave -noupdate -group soc_interconnect -group interleaved_masters3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[3]/wdata}
add wave -noupdate -group soc_interconnect -group interleaved_masters3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[3]/be}
add wave -noupdate -group soc_interconnect -group interleaved_masters3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[3]/gnt}
add wave -noupdate -group soc_interconnect -group interleaved_masters3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[3]/r_opc}
add wave -noupdate -group soc_interconnect -group interleaved_masters3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[3]/r_rdata}
add wave -noupdate -group soc_interconnect -group interleaved_masters3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[3]/r_valid}
add wave -noupdate -group soc_interconnect -group interleaved_masters4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[4]/req}
add wave -noupdate -group soc_interconnect -group interleaved_masters4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[4]/add}
add wave -noupdate -group soc_interconnect -group interleaved_masters4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[4]/wen}
add wave -noupdate -group soc_interconnect -group interleaved_masters4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[4]/wdata}
add wave -noupdate -group soc_interconnect -group interleaved_masters4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[4]/be}
add wave -noupdate -group soc_interconnect -group interleaved_masters4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[4]/gnt}
add wave -noupdate -group soc_interconnect -group interleaved_masters4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[4]/r_opc}
add wave -noupdate -group soc_interconnect -group interleaved_masters4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[4]/r_rdata}
add wave -noupdate -group soc_interconnect -group interleaved_masters4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[4]/r_valid}
add wave -noupdate -group soc_interconnect -group interleaved_masters5 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[5]/req}
add wave -noupdate -group soc_interconnect -group interleaved_masters5 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[5]/add}
add wave -noupdate -group soc_interconnect -group interleaved_masters5 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[5]/wen}
add wave -noupdate -group soc_interconnect -group interleaved_masters5 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[5]/wdata}
add wave -noupdate -group soc_interconnect -group interleaved_masters5 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[5]/be}
add wave -noupdate -group soc_interconnect -group interleaved_masters5 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[5]/gnt}
add wave -noupdate -group soc_interconnect -group interleaved_masters5 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[5]/r_opc}
add wave -noupdate -group soc_interconnect -group interleaved_masters5 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[5]/r_rdata}
add wave -noupdate -group soc_interconnect -group interleaved_masters5 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[5]/r_valid}
add wave -noupdate -group soc_interconnect -group interleaved_masters6 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[6]/req}
add wave -noupdate -group soc_interconnect -group interleaved_masters6 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[6]/add}
add wave -noupdate -group soc_interconnect -group interleaved_masters6 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[6]/wen}
add wave -noupdate -group soc_interconnect -group interleaved_masters6 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[6]/wdata}
add wave -noupdate -group soc_interconnect -group interleaved_masters6 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[6]/be}
add wave -noupdate -group soc_interconnect -group interleaved_masters6 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[6]/gnt}
add wave -noupdate -group soc_interconnect -group interleaved_masters6 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[6]/r_opc}
add wave -noupdate -group soc_interconnect -group interleaved_masters6 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[6]/r_rdata}
add wave -noupdate -group soc_interconnect -group interleaved_masters6 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[6]/r_valid}
add wave -noupdate -group soc_interconnect -group interleaved_masters7 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[7]/req}
add wave -noupdate -group soc_interconnect -group interleaved_masters7 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[7]/add}
add wave -noupdate -group soc_interconnect -group interleaved_masters7 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[7]/wen}
add wave -noupdate -group soc_interconnect -group interleaved_masters7 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[7]/wdata}
add wave -noupdate -group soc_interconnect -group interleaved_masters7 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[7]/be}
add wave -noupdate -group soc_interconnect -group interleaved_masters7 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[7]/gnt}
add wave -noupdate -group soc_interconnect -group interleaved_masters7 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[7]/r_opc}
add wave -noupdate -group soc_interconnect -group interleaved_masters7 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[7]/r_rdata}
add wave -noupdate -group soc_interconnect -group interleaved_masters7 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[7]/r_valid}
add wave -noupdate -group soc_interconnect -group interleaved_masters8 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[8]/req}
add wave -noupdate -group soc_interconnect -group interleaved_masters8 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[8]/add}
add wave -noupdate -group soc_interconnect -group interleaved_masters8 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[8]/wen}
add wave -noupdate -group soc_interconnect -group interleaved_masters8 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[8]/wdata}
add wave -noupdate -group soc_interconnect -group interleaved_masters8 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[8]/be}
add wave -noupdate -group soc_interconnect -group interleaved_masters8 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[8]/gnt}
add wave -noupdate -group soc_interconnect -group interleaved_masters8 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[8]/r_opc}
add wave -noupdate -group soc_interconnect -group interleaved_masters8 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[8]/r_rdata}
add wave -noupdate -group soc_interconnect -group interleaved_masters8 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_masters[8]/r_valid}
add wave -noupdate -group soc_interconnect -group interleaved_slaves0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_slaves[0]/req}
add wave -noupdate -group soc_interconnect -group interleaved_slaves0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_slaves[0]/add}
add wave -noupdate -group soc_interconnect -group interleaved_slaves0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_slaves[0]/wen}
add wave -noupdate -group soc_interconnect -group interleaved_slaves0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_slaves[0]/wdata}
add wave -noupdate -group soc_interconnect -group interleaved_slaves0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_slaves[0]/be}
add wave -noupdate -group soc_interconnect -group interleaved_slaves0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_slaves[0]/gnt}
add wave -noupdate -group soc_interconnect -group interleaved_slaves0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_slaves[0]/r_opc}
add wave -noupdate -group soc_interconnect -group interleaved_slaves0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_slaves[0]/r_rdata}
add wave -noupdate -group soc_interconnect -group interleaved_slaves0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_slaves[0]/r_valid}
add wave -noupdate -group soc_interconnect -group interleaved_slaves1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_slaves[1]/req}
add wave -noupdate -group soc_interconnect -group interleaved_slaves1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_slaves[1]/add}
add wave -noupdate -group soc_interconnect -group interleaved_slaves1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_slaves[1]/wen}
add wave -noupdate -group soc_interconnect -group interleaved_slaves1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_slaves[1]/wdata}
add wave -noupdate -group soc_interconnect -group interleaved_slaves1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_slaves[1]/be}
add wave -noupdate -group soc_interconnect -group interleaved_slaves1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_slaves[1]/gnt}
add wave -noupdate -group soc_interconnect -group interleaved_slaves1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_slaves[1]/r_opc}
add wave -noupdate -group soc_interconnect -group interleaved_slaves1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_slaves[1]/r_rdata}
add wave -noupdate -group soc_interconnect -group interleaved_slaves1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_slaves[1]/r_valid}
add wave -noupdate -group soc_interconnect -group interleaved_slaves2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_slaves[2]/req}
add wave -noupdate -group soc_interconnect -group interleaved_slaves2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_slaves[2]/add}
add wave -noupdate -group soc_interconnect -group interleaved_slaves2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_slaves[2]/wen}
add wave -noupdate -group soc_interconnect -group interleaved_slaves2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_slaves[2]/wdata}
add wave -noupdate -group soc_interconnect -group interleaved_slaves2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_slaves[2]/be}
add wave -noupdate -group soc_interconnect -group interleaved_slaves2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_slaves[2]/gnt}
add wave -noupdate -group soc_interconnect -group interleaved_slaves2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_slaves[2]/r_opc}
add wave -noupdate -group soc_interconnect -group interleaved_slaves2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_slaves[2]/r_rdata}
add wave -noupdate -group soc_interconnect -group interleaved_slaves2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_slaves[2]/r_valid}
add wave -noupdate -group soc_interconnect -group interleaved_slaves3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_slaves[3]/req}
add wave -noupdate -group soc_interconnect -group interleaved_slaves3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_slaves[3]/add}
add wave -noupdate -group soc_interconnect -group interleaved_slaves3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_slaves[3]/wen}
add wave -noupdate -group soc_interconnect -group interleaved_slaves3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_slaves[3]/wdata}
add wave -noupdate -group soc_interconnect -group interleaved_slaves3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_slaves[3]/be}
add wave -noupdate -group soc_interconnect -group interleaved_slaves3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_slaves[3]/gnt}
add wave -noupdate -group soc_interconnect -group interleaved_slaves3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_slaves[3]/r_opc}
add wave -noupdate -group soc_interconnect -group interleaved_slaves3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_slaves[3]/r_rdata}
add wave -noupdate -group soc_interconnect -group interleaved_slaves3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/interleaved_slaves[3]/r_valid}
add wave -noupdate -group soc_interconnect -group master_ports0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/master_ports[0]/req}
add wave -noupdate -group soc_interconnect -group master_ports0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/master_ports[0]/add}
add wave -noupdate -group soc_interconnect -group master_ports0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/master_ports[0]/wen}
add wave -noupdate -group soc_interconnect -group master_ports0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/master_ports[0]/wdata}
add wave -noupdate -group soc_interconnect -group master_ports0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/master_ports[0]/be}
add wave -noupdate -group soc_interconnect -group master_ports0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/master_ports[0]/gnt}
add wave -noupdate -group soc_interconnect -group master_ports0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/master_ports[0]/r_opc}
add wave -noupdate -group soc_interconnect -group master_ports0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/master_ports[0]/r_rdata}
add wave -noupdate -group soc_interconnect -group master_ports0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/master_ports[0]/r_valid}
add wave -noupdate -group soc_interconnect -group master_ports1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/master_ports[1]/req}
add wave -noupdate -group soc_interconnect -group master_ports1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/master_ports[1]/add}
add wave -noupdate -group soc_interconnect -group master_ports1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/master_ports[1]/wen}
add wave -noupdate -group soc_interconnect -group master_ports1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/master_ports[1]/wdata}
add wave -noupdate -group soc_interconnect -group master_ports1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/master_ports[1]/be}
add wave -noupdate -group soc_interconnect -group master_ports1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/master_ports[1]/gnt}
add wave -noupdate -group soc_interconnect -group master_ports1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/master_ports[1]/r_opc}
add wave -noupdate -group soc_interconnect -group master_ports1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/master_ports[1]/r_rdata}
add wave -noupdate -group soc_interconnect -group master_ports1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/master_ports[1]/r_valid}
add wave -noupdate -group soc_interconnect -group master_ports2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/master_ports[2]/req}
add wave -noupdate -group soc_interconnect -group master_ports2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/master_ports[2]/add}
add wave -noupdate -group soc_interconnect -group master_ports2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/master_ports[2]/wen}
add wave -noupdate -group soc_interconnect -group master_ports2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/master_ports[2]/wdata}
add wave -noupdate -group soc_interconnect -group master_ports2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/master_ports[2]/be}
add wave -noupdate -group soc_interconnect -group master_ports2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/master_ports[2]/gnt}
add wave -noupdate -group soc_interconnect -group master_ports2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/master_ports[2]/r_opc}
add wave -noupdate -group soc_interconnect -group master_ports2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/master_ports[2]/r_rdata}
add wave -noupdate -group soc_interconnect -group master_ports2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/master_ports[2]/r_valid}
add wave -noupdate -group soc_interconnect -group master_ports3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/master_ports[3]/req}
add wave -noupdate -group soc_interconnect -group master_ports3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/master_ports[3]/add}
add wave -noupdate -group soc_interconnect -group master_ports3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/master_ports[3]/wen}
add wave -noupdate -group soc_interconnect -group master_ports3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/master_ports[3]/wdata}
add wave -noupdate -group soc_interconnect -group master_ports3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/master_ports[3]/be}
add wave -noupdate -group soc_interconnect -group master_ports3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/master_ports[3]/gnt}
add wave -noupdate -group soc_interconnect -group master_ports3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/master_ports[3]/r_opc}
add wave -noupdate -group soc_interconnect -group master_ports3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/master_ports[3]/r_rdata}
add wave -noupdate -group soc_interconnect -group master_ports3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/master_ports[3]/r_valid}
add wave -noupdate -group soc_interconnect -group master_ports4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/master_ports[4]/req}
add wave -noupdate -group soc_interconnect -group master_ports4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/master_ports[4]/add}
add wave -noupdate -group soc_interconnect -group master_ports4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/master_ports[4]/wen}
add wave -noupdate -group soc_interconnect -group master_ports4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/master_ports[4]/wdata}
add wave -noupdate -group soc_interconnect -group master_ports4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/master_ports[4]/be}
add wave -noupdate -group soc_interconnect -group master_ports4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/master_ports[4]/gnt}
add wave -noupdate -group soc_interconnect -group master_ports4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/master_ports[4]/r_opc}
add wave -noupdate -group soc_interconnect -group master_ports4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/master_ports[4]/r_rdata}
add wave -noupdate -group soc_interconnect -group master_ports4 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/i_soc_interconnect/master_ports[4]/r_valid}
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {52879785 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 250
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {51920005 ps} {53974745 ps}
