onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -group soc_interconnect_wrap /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/clk_i
add wave -noupdate -group soc_interconnect_wrap /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/rst_ni
add wave -noupdate -group soc_interconnect_wrap /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/test_en_i
add wave -noupdate -group soc_interconnect_wrap -group axi_master_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_in_bus/AXI_ADDR_WIDTH
add wave -noupdate -group soc_interconnect_wrap -group axi_master_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_in_bus/AXI_DATA_WIDTH
add wave -noupdate -group soc_interconnect_wrap -group axi_master_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_in_bus/AXI_ID_WIDTH
add wave -noupdate -group soc_interconnect_wrap -group axi_master_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_in_bus/AXI_USER_WIDTH
add wave -noupdate -group soc_interconnect_wrap -group axi_master_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_in_bus/AXI_STRB_WIDTH
add wave -noupdate -group soc_interconnect_wrap -group axi_master_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_in_bus/aw_id
add wave -noupdate -group soc_interconnect_wrap -group axi_master_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_in_bus/aw_addr
add wave -noupdate -group soc_interconnect_wrap -group axi_master_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_in_bus/aw_len
add wave -noupdate -group soc_interconnect_wrap -group axi_master_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_in_bus/aw_size
add wave -noupdate -group soc_interconnect_wrap -group axi_master_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_in_bus/aw_burst
add wave -noupdate -group soc_interconnect_wrap -group axi_master_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_in_bus/aw_lock
add wave -noupdate -group soc_interconnect_wrap -group axi_master_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_in_bus/aw_cache
add wave -noupdate -group soc_interconnect_wrap -group axi_master_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_in_bus/aw_prot
add wave -noupdate -group soc_interconnect_wrap -group axi_master_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_in_bus/aw_qos
add wave -noupdate -group soc_interconnect_wrap -group axi_master_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_in_bus/aw_region
add wave -noupdate -group soc_interconnect_wrap -group axi_master_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_in_bus/aw_atop
add wave -noupdate -group soc_interconnect_wrap -group axi_master_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_in_bus/aw_user
add wave -noupdate -group soc_interconnect_wrap -group axi_master_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_in_bus/aw_valid
add wave -noupdate -group soc_interconnect_wrap -group axi_master_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_in_bus/aw_ready
add wave -noupdate -group soc_interconnect_wrap -group axi_master_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_in_bus/w_data
add wave -noupdate -group soc_interconnect_wrap -group axi_master_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_in_bus/w_strb
add wave -noupdate -group soc_interconnect_wrap -group axi_master_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_in_bus/w_last
add wave -noupdate -group soc_interconnect_wrap -group axi_master_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_in_bus/w_user
add wave -noupdate -group soc_interconnect_wrap -group axi_master_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_in_bus/w_valid
add wave -noupdate -group soc_interconnect_wrap -group axi_master_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_in_bus/w_ready
add wave -noupdate -group soc_interconnect_wrap -group axi_master_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_in_bus/b_id
add wave -noupdate -group soc_interconnect_wrap -group axi_master_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_in_bus/b_resp
add wave -noupdate -group soc_interconnect_wrap -group axi_master_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_in_bus/b_user
add wave -noupdate -group soc_interconnect_wrap -group axi_master_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_in_bus/b_valid
add wave -noupdate -group soc_interconnect_wrap -group axi_master_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_in_bus/b_ready
add wave -noupdate -group soc_interconnect_wrap -group axi_master_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_in_bus/ar_id
add wave -noupdate -group soc_interconnect_wrap -group axi_master_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_in_bus/ar_addr
add wave -noupdate -group soc_interconnect_wrap -group axi_master_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_in_bus/ar_len
add wave -noupdate -group soc_interconnect_wrap -group axi_master_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_in_bus/ar_size
add wave -noupdate -group soc_interconnect_wrap -group axi_master_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_in_bus/ar_burst
add wave -noupdate -group soc_interconnect_wrap -group axi_master_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_in_bus/ar_lock
add wave -noupdate -group soc_interconnect_wrap -group axi_master_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_in_bus/ar_cache
add wave -noupdate -group soc_interconnect_wrap -group axi_master_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_in_bus/ar_prot
add wave -noupdate -group soc_interconnect_wrap -group axi_master_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_in_bus/ar_qos
add wave -noupdate -group soc_interconnect_wrap -group axi_master_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_in_bus/ar_region
add wave -noupdate -group soc_interconnect_wrap -group axi_master_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_in_bus/ar_user
add wave -noupdate -group soc_interconnect_wrap -group axi_master_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_in_bus/ar_valid
add wave -noupdate -group soc_interconnect_wrap -group axi_master_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_in_bus/ar_ready
add wave -noupdate -group soc_interconnect_wrap -group axi_master_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_in_bus/r_id
add wave -noupdate -group soc_interconnect_wrap -group axi_master_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_in_bus/r_data
add wave -noupdate -group soc_interconnect_wrap -group axi_master_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_in_bus/r_resp
add wave -noupdate -group soc_interconnect_wrap -group axi_master_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_in_bus/r_last
add wave -noupdate -group soc_interconnect_wrap -group axi_master_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_in_bus/r_user
add wave -noupdate -group soc_interconnect_wrap -group axi_master_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_in_bus/r_valid
add wave -noupdate -group soc_interconnect_wrap -group axi_master_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_in_bus/r_ready
add wave -noupdate -group soc_interconnect_wrap -group axi_slave_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_out_bus/AXI_ADDR_WIDTH
add wave -noupdate -group soc_interconnect_wrap -group axi_slave_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_out_bus/AXI_DATA_WIDTH
add wave -noupdate -group soc_interconnect_wrap -group axi_slave_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_out_bus/AXI_ID_WIDTH
add wave -noupdate -group soc_interconnect_wrap -group axi_slave_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_out_bus/AXI_USER_WIDTH
add wave -noupdate -group soc_interconnect_wrap -group axi_slave_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_out_bus/AXI_STRB_WIDTH
add wave -noupdate -group soc_interconnect_wrap -group axi_slave_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_out_bus/aw_id
add wave -noupdate -group soc_interconnect_wrap -group axi_slave_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_out_bus/aw_addr
add wave -noupdate -group soc_interconnect_wrap -group axi_slave_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_out_bus/aw_len
add wave -noupdate -group soc_interconnect_wrap -group axi_slave_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_out_bus/aw_size
add wave -noupdate -group soc_interconnect_wrap -group axi_slave_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_out_bus/aw_burst
add wave -noupdate -group soc_interconnect_wrap -group axi_slave_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_out_bus/aw_lock
add wave -noupdate -group soc_interconnect_wrap -group axi_slave_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_out_bus/aw_cache
add wave -noupdate -group soc_interconnect_wrap -group axi_slave_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_out_bus/aw_prot
add wave -noupdate -group soc_interconnect_wrap -group axi_slave_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_out_bus/aw_qos
add wave -noupdate -group soc_interconnect_wrap -group axi_slave_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_out_bus/aw_region
add wave -noupdate -group soc_interconnect_wrap -group axi_slave_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_out_bus/aw_atop
add wave -noupdate -group soc_interconnect_wrap -group axi_slave_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_out_bus/aw_user
add wave -noupdate -group soc_interconnect_wrap -group axi_slave_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_out_bus/aw_valid
add wave -noupdate -group soc_interconnect_wrap -group axi_slave_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_out_bus/aw_ready
add wave -noupdate -group soc_interconnect_wrap -group axi_slave_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_out_bus/w_data
add wave -noupdate -group soc_interconnect_wrap -group axi_slave_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_out_bus/w_strb
add wave -noupdate -group soc_interconnect_wrap -group axi_slave_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_out_bus/w_last
add wave -noupdate -group soc_interconnect_wrap -group axi_slave_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_out_bus/w_user
add wave -noupdate -group soc_interconnect_wrap -group axi_slave_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_out_bus/w_valid
add wave -noupdate -group soc_interconnect_wrap -group axi_slave_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_out_bus/w_ready
add wave -noupdate -group soc_interconnect_wrap -group axi_slave_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_out_bus/b_id
add wave -noupdate -group soc_interconnect_wrap -group axi_slave_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_out_bus/b_resp
add wave -noupdate -group soc_interconnect_wrap -group axi_slave_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_out_bus/b_user
add wave -noupdate -group soc_interconnect_wrap -group axi_slave_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_out_bus/b_valid
add wave -noupdate -group soc_interconnect_wrap -group axi_slave_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_out_bus/b_ready
add wave -noupdate -group soc_interconnect_wrap -group axi_slave_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_out_bus/ar_id
add wave -noupdate -group soc_interconnect_wrap -group axi_slave_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_out_bus/ar_addr
add wave -noupdate -group soc_interconnect_wrap -group axi_slave_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_out_bus/ar_len
add wave -noupdate -group soc_interconnect_wrap -group axi_slave_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_out_bus/ar_size
add wave -noupdate -group soc_interconnect_wrap -group axi_slave_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_out_bus/ar_burst
add wave -noupdate -group soc_interconnect_wrap -group axi_slave_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_out_bus/ar_lock
add wave -noupdate -group soc_interconnect_wrap -group axi_slave_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_out_bus/ar_cache
add wave -noupdate -group soc_interconnect_wrap -group axi_slave_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_out_bus/ar_prot
add wave -noupdate -group soc_interconnect_wrap -group axi_slave_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_out_bus/ar_qos
add wave -noupdate -group soc_interconnect_wrap -group axi_slave_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_out_bus/ar_region
add wave -noupdate -group soc_interconnect_wrap -group axi_slave_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_out_bus/ar_user
add wave -noupdate -group soc_interconnect_wrap -group axi_slave_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_out_bus/ar_valid
add wave -noupdate -group soc_interconnect_wrap -group axi_slave_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_out_bus/ar_ready
add wave -noupdate -group soc_interconnect_wrap -group axi_slave_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_out_bus/r_id
add wave -noupdate -group soc_interconnect_wrap -group axi_slave_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_out_bus/r_data
add wave -noupdate -group soc_interconnect_wrap -group axi_slave_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_out_bus/r_resp
add wave -noupdate -group soc_interconnect_wrap -group axi_slave_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_out_bus/r_last
add wave -noupdate -group soc_interconnect_wrap -group axi_slave_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_out_bus/r_user
add wave -noupdate -group soc_interconnect_wrap -group axi_slave_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_out_bus/r_valid
add wave -noupdate -group soc_interconnect_wrap -group axi_slave_plug /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_data_out_bus/r_ready
add wave -noupdate -group soc_interconnect_wrap -group boot_rom_slave /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_rom_bus/req
add wave -noupdate -group soc_interconnect_wrap -group boot_rom_slave /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_rom_bus/add
add wave -noupdate -group soc_interconnect_wrap -group boot_rom_slave /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_rom_bus/wen
add wave -noupdate -group soc_interconnect_wrap -group boot_rom_slave /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_rom_bus/wdata
add wave -noupdate -group soc_interconnect_wrap -group boot_rom_slave /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_rom_bus/be
add wave -noupdate -group soc_interconnect_wrap -group boot_rom_slave /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_rom_bus/gnt
add wave -noupdate -group soc_interconnect_wrap -group boot_rom_slave /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_rom_bus/r_opc
add wave -noupdate -group soc_interconnect_wrap -group boot_rom_slave /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_rom_bus/r_rdata
add wave -noupdate -group soc_interconnect_wrap -group boot_rom_slave /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_rom_bus/r_valid
add wave -noupdate -group soc_interconnect_wrap -group apb_peripheral_bus /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_apb_periph_bus/APB_ADDR_WIDTH
add wave -noupdate -group soc_interconnect_wrap -group apb_peripheral_bus /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_apb_periph_bus/APB_DATA_WIDTH
add wave -noupdate -group soc_interconnect_wrap -group apb_peripheral_bus /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_apb_periph_bus/paddr
add wave -noupdate -group soc_interconnect_wrap -group apb_peripheral_bus /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_apb_periph_bus/pwdata
add wave -noupdate -group soc_interconnect_wrap -group apb_peripheral_bus /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_apb_periph_bus/pwrite
add wave -noupdate -group soc_interconnect_wrap -group apb_peripheral_bus /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_apb_periph_bus/psel
add wave -noupdate -group soc_interconnect_wrap -group apb_peripheral_bus /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_apb_periph_bus/penable
add wave -noupdate -group soc_interconnect_wrap -group apb_peripheral_bus /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_apb_periph_bus/prdata
add wave -noupdate -group soc_interconnect_wrap -group apb_peripheral_bus /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_apb_periph_bus/pready
add wave -noupdate -group soc_interconnect_wrap -group apb_peripheral_bus /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_apb_periph_bus/pslverr
add wave -noupdate -group soc_interconnect_wrap -group interleaved_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_l2_bus[3]/req}
add wave -noupdate -group soc_interconnect_wrap -group interleaved_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_l2_bus[3]/add}
add wave -noupdate -group soc_interconnect_wrap -group interleaved_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_l2_bus[3]/wen}
add wave -noupdate -group soc_interconnect_wrap -group interleaved_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_l2_bus[3]/wdata}
add wave -noupdate -group soc_interconnect_wrap -group interleaved_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_l2_bus[3]/be}
add wave -noupdate -group soc_interconnect_wrap -group interleaved_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_l2_bus[3]/gnt}
add wave -noupdate -group soc_interconnect_wrap -group interleaved_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_l2_bus[3]/r_opc}
add wave -noupdate -group soc_interconnect_wrap -group interleaved_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_l2_bus[3]/r_rdata}
add wave -noupdate -group soc_interconnect_wrap -group interleaved_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_l2_bus[3]/r_valid}
add wave -noupdate -group soc_interconnect_wrap -group interleaved_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_l2_bus[2]/req}
add wave -noupdate -group soc_interconnect_wrap -group interleaved_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_l2_bus[2]/add}
add wave -noupdate -group soc_interconnect_wrap -group interleaved_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_l2_bus[2]/wen}
add wave -noupdate -group soc_interconnect_wrap -group interleaved_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_l2_bus[2]/wdata}
add wave -noupdate -group soc_interconnect_wrap -group interleaved_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_l2_bus[2]/be}
add wave -noupdate -group soc_interconnect_wrap -group interleaved_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_l2_bus[2]/gnt}
add wave -noupdate -group soc_interconnect_wrap -group interleaved_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_l2_bus[2]/r_opc}
add wave -noupdate -group soc_interconnect_wrap -group interleaved_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_l2_bus[2]/r_rdata}
add wave -noupdate -group soc_interconnect_wrap -group interleaved_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_l2_bus[2]/r_valid}
add wave -noupdate -group soc_interconnect_wrap -group interleaved_slave2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_l2_bus[1]/req}
add wave -noupdate -group soc_interconnect_wrap -group interleaved_slave2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_l2_bus[1]/add}
add wave -noupdate -group soc_interconnect_wrap -group interleaved_slave2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_l2_bus[1]/wen}
add wave -noupdate -group soc_interconnect_wrap -group interleaved_slave2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_l2_bus[1]/wdata}
add wave -noupdate -group soc_interconnect_wrap -group interleaved_slave2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_l2_bus[1]/be}
add wave -noupdate -group soc_interconnect_wrap -group interleaved_slave2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_l2_bus[1]/gnt}
add wave -noupdate -group soc_interconnect_wrap -group interleaved_slave2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_l2_bus[1]/r_opc}
add wave -noupdate -group soc_interconnect_wrap -group interleaved_slave2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_l2_bus[1]/r_rdata}
add wave -noupdate -group soc_interconnect_wrap -group interleaved_slave2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_l2_bus[1]/r_valid}
add wave -noupdate -group soc_interconnect_wrap -group interleaved_slave3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_l2_bus[0]/req}
add wave -noupdate -group soc_interconnect_wrap -group interleaved_slave3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_l2_bus[0]/add}
add wave -noupdate -group soc_interconnect_wrap -group interleaved_slave3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_l2_bus[0]/wen}
add wave -noupdate -group soc_interconnect_wrap -group interleaved_slave3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_l2_bus[0]/wdata}
add wave -noupdate -group soc_interconnect_wrap -group interleaved_slave3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_l2_bus[0]/be}
add wave -noupdate -group soc_interconnect_wrap -group interleaved_slave3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_l2_bus[0]/gnt}
add wave -noupdate -group soc_interconnect_wrap -group interleaved_slave3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_l2_bus[0]/r_opc}
add wave -noupdate -group soc_interconnect_wrap -group interleaved_slave3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_l2_bus[0]/r_rdata}
add wave -noupdate -group soc_interconnect_wrap -group interleaved_slave3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_l2_bus[0]/r_valid}
add wave -noupdate -group soc_interconnect_wrap -group private_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_l2_pri_bus[1]/req}
add wave -noupdate -group soc_interconnect_wrap -group private_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_l2_pri_bus[1]/add}
add wave -noupdate -group soc_interconnect_wrap -group private_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_l2_pri_bus[1]/wen}
add wave -noupdate -group soc_interconnect_wrap -group private_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_l2_pri_bus[1]/wdata}
add wave -noupdate -group soc_interconnect_wrap -group private_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_l2_pri_bus[1]/be}
add wave -noupdate -group soc_interconnect_wrap -group private_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_l2_pri_bus[1]/gnt}
add wave -noupdate -group soc_interconnect_wrap -group private_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_l2_pri_bus[1]/r_opc}
add wave -noupdate -group soc_interconnect_wrap -group private_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_l2_pri_bus[1]/r_rdata}
add wave -noupdate -group soc_interconnect_wrap -group private_slave0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_l2_pri_bus[1]/r_valid}
add wave -noupdate -group soc_interconnect_wrap -group private_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_l2_pri_bus[0]/req}
add wave -noupdate -group soc_interconnect_wrap -group private_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_l2_pri_bus[0]/add}
add wave -noupdate -group soc_interconnect_wrap -group private_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_l2_pri_bus[0]/wen}
add wave -noupdate -group soc_interconnect_wrap -group private_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_l2_pri_bus[0]/wdata}
add wave -noupdate -group soc_interconnect_wrap -group private_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_l2_pri_bus[0]/be}
add wave -noupdate -group soc_interconnect_wrap -group private_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_l2_pri_bus[0]/gnt}
add wave -noupdate -group soc_interconnect_wrap -group private_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_l2_pri_bus[0]/r_opc}
add wave -noupdate -group soc_interconnect_wrap -group private_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_l2_pri_bus[0]/r_rdata}
add wave -noupdate -group soc_interconnect_wrap -group private_slave1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_mem_l2_pri_bus[0]/r_valid}
add wave -noupdate -group soc_interconnect_wrap -group tcdm_debug_master /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_lint_debug_bus/req
add wave -noupdate -group soc_interconnect_wrap -group tcdm_debug_master /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_lint_debug_bus/add
add wave -noupdate -group soc_interconnect_wrap -group tcdm_debug_master /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_lint_debug_bus/wen
add wave -noupdate -group soc_interconnect_wrap -group tcdm_debug_master /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_lint_debug_bus/wdata
add wave -noupdate -group soc_interconnect_wrap -group tcdm_debug_master /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_lint_debug_bus/be
add wave -noupdate -group soc_interconnect_wrap -group tcdm_debug_master /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_lint_debug_bus/gnt
add wave -noupdate -group soc_interconnect_wrap -group tcdm_debug_master /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_lint_debug_bus/r_opc
add wave -noupdate -group soc_interconnect_wrap -group tcdm_debug_master /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_lint_debug_bus/r_rdata
add wave -noupdate -group soc_interconnect_wrap -group tcdm_debug_master /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_lint_debug_bus/r_valid
add wave -noupdate -group soc_interconnect_wrap -group tcdm_fc_data /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_lint_fc_data_bus/req
add wave -noupdate -group soc_interconnect_wrap -group tcdm_fc_data /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_lint_fc_data_bus/add
add wave -noupdate -group soc_interconnect_wrap -group tcdm_fc_data /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_lint_fc_data_bus/wen
add wave -noupdate -group soc_interconnect_wrap -group tcdm_fc_data /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_lint_fc_data_bus/wdata
add wave -noupdate -group soc_interconnect_wrap -group tcdm_fc_data /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_lint_fc_data_bus/be
add wave -noupdate -group soc_interconnect_wrap -group tcdm_fc_data /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_lint_fc_data_bus/gnt
add wave -noupdate -group soc_interconnect_wrap -group tcdm_fc_data /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_lint_fc_data_bus/r_opc
add wave -noupdate -group soc_interconnect_wrap -group tcdm_fc_data /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_lint_fc_data_bus/r_rdata
add wave -noupdate -group soc_interconnect_wrap -group tcdm_fc_data /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_lint_fc_data_bus/r_valid
add wave -noupdate -group soc_interconnect_wrap -group tcdm_fc_instr /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_lint_fc_instr_bus/req
add wave -noupdate -group soc_interconnect_wrap -group tcdm_fc_instr /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_lint_fc_instr_bus/add
add wave -noupdate -group soc_interconnect_wrap -group tcdm_fc_instr /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_lint_fc_instr_bus/wen
add wave -noupdate -group soc_interconnect_wrap -group tcdm_fc_instr /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_lint_fc_instr_bus/wdata
add wave -noupdate -group soc_interconnect_wrap -group tcdm_fc_instr /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_lint_fc_instr_bus/be
add wave -noupdate -group soc_interconnect_wrap -group tcdm_fc_instr /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_lint_fc_instr_bus/gnt
add wave -noupdate -group soc_interconnect_wrap -group tcdm_fc_instr /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_lint_fc_instr_bus/r_opc
add wave -noupdate -group soc_interconnect_wrap -group tcdm_fc_instr /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_lint_fc_instr_bus/r_rdata
add wave -noupdate -group soc_interconnect_wrap -group tcdm_fc_instr /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_lint_fc_instr_bus/r_valid
add wave -noupdate -group soc_interconnect_wrap -group tcdm_udma_rx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_lint_udma_rx_bus/req
add wave -noupdate -group soc_interconnect_wrap -group tcdm_udma_rx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_lint_udma_rx_bus/add
add wave -noupdate -group soc_interconnect_wrap -group tcdm_udma_rx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_lint_udma_rx_bus/wen
add wave -noupdate -group soc_interconnect_wrap -group tcdm_udma_rx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_lint_udma_rx_bus/wdata
add wave -noupdate -group soc_interconnect_wrap -group tcdm_udma_rx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_lint_udma_rx_bus/be
add wave -noupdate -group soc_interconnect_wrap -group tcdm_udma_rx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_lint_udma_rx_bus/gnt
add wave -noupdate -group soc_interconnect_wrap -group tcdm_udma_rx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_lint_udma_rx_bus/r_opc
add wave -noupdate -group soc_interconnect_wrap -group tcdm_udma_rx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_lint_udma_rx_bus/r_rdata
add wave -noupdate -group soc_interconnect_wrap -group tcdm_udma_rx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_lint_udma_rx_bus/r_valid
add wave -noupdate -group soc_interconnect_wrap -group tcdm_udma_tx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_lint_udma_tx_bus/req
add wave -noupdate -group soc_interconnect_wrap -group tcdm_udma_tx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_lint_udma_tx_bus/add
add wave -noupdate -group soc_interconnect_wrap -group tcdm_udma_tx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_lint_udma_tx_bus/wen
add wave -noupdate -group soc_interconnect_wrap -group tcdm_udma_tx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_lint_udma_tx_bus/wdata
add wave -noupdate -group soc_interconnect_wrap -group tcdm_udma_tx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_lint_udma_tx_bus/be
add wave -noupdate -group soc_interconnect_wrap -group tcdm_udma_tx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_lint_udma_tx_bus/gnt
add wave -noupdate -group soc_interconnect_wrap -group tcdm_udma_tx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_lint_udma_tx_bus/r_opc
add wave -noupdate -group soc_interconnect_wrap -group tcdm_udma_tx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_lint_udma_tx_bus/r_rdata
add wave -noupdate -group soc_interconnect_wrap -group tcdm_udma_tx /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/s_lint_udma_tx_bus/r_valid
add wave -noupdate -group soc_interconnect_wrap -group axi_to_axi_lite_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_to_axi_lite_bridge/AXI_ADDR_WIDTH
add wave -noupdate -group soc_interconnect_wrap -group axi_to_axi_lite_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_to_axi_lite_bridge/AXI_DATA_WIDTH
add wave -noupdate -group soc_interconnect_wrap -group axi_to_axi_lite_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_to_axi_lite_bridge/AXI_ID_WIDTH
add wave -noupdate -group soc_interconnect_wrap -group axi_to_axi_lite_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_to_axi_lite_bridge/AXI_USER_WIDTH
add wave -noupdate -group soc_interconnect_wrap -group axi_to_axi_lite_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_to_axi_lite_bridge/AXI_STRB_WIDTH
add wave -noupdate -group soc_interconnect_wrap -group axi_to_axi_lite_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_to_axi_lite_bridge/aw_id
add wave -noupdate -group soc_interconnect_wrap -group axi_to_axi_lite_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_to_axi_lite_bridge/aw_addr
add wave -noupdate -group soc_interconnect_wrap -group axi_to_axi_lite_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_to_axi_lite_bridge/aw_len
add wave -noupdate -group soc_interconnect_wrap -group axi_to_axi_lite_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_to_axi_lite_bridge/aw_size
add wave -noupdate -group soc_interconnect_wrap -group axi_to_axi_lite_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_to_axi_lite_bridge/aw_burst
add wave -noupdate -group soc_interconnect_wrap -group axi_to_axi_lite_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_to_axi_lite_bridge/aw_lock
add wave -noupdate -group soc_interconnect_wrap -group axi_to_axi_lite_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_to_axi_lite_bridge/aw_cache
add wave -noupdate -group soc_interconnect_wrap -group axi_to_axi_lite_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_to_axi_lite_bridge/aw_prot
add wave -noupdate -group soc_interconnect_wrap -group axi_to_axi_lite_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_to_axi_lite_bridge/aw_qos
add wave -noupdate -group soc_interconnect_wrap -group axi_to_axi_lite_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_to_axi_lite_bridge/aw_region
add wave -noupdate -group soc_interconnect_wrap -group axi_to_axi_lite_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_to_axi_lite_bridge/aw_atop
add wave -noupdate -group soc_interconnect_wrap -group axi_to_axi_lite_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_to_axi_lite_bridge/aw_user
add wave -noupdate -group soc_interconnect_wrap -group axi_to_axi_lite_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_to_axi_lite_bridge/aw_valid
add wave -noupdate -group soc_interconnect_wrap -group axi_to_axi_lite_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_to_axi_lite_bridge/aw_ready
add wave -noupdate -group soc_interconnect_wrap -group axi_to_axi_lite_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_to_axi_lite_bridge/w_data
add wave -noupdate -group soc_interconnect_wrap -group axi_to_axi_lite_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_to_axi_lite_bridge/w_strb
add wave -noupdate -group soc_interconnect_wrap -group axi_to_axi_lite_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_to_axi_lite_bridge/w_last
add wave -noupdate -group soc_interconnect_wrap -group axi_to_axi_lite_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_to_axi_lite_bridge/w_user
add wave -noupdate -group soc_interconnect_wrap -group axi_to_axi_lite_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_to_axi_lite_bridge/w_valid
add wave -noupdate -group soc_interconnect_wrap -group axi_to_axi_lite_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_to_axi_lite_bridge/w_ready
add wave -noupdate -group soc_interconnect_wrap -group axi_to_axi_lite_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_to_axi_lite_bridge/b_id
add wave -noupdate -group soc_interconnect_wrap -group axi_to_axi_lite_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_to_axi_lite_bridge/b_resp
add wave -noupdate -group soc_interconnect_wrap -group axi_to_axi_lite_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_to_axi_lite_bridge/b_user
add wave -noupdate -group soc_interconnect_wrap -group axi_to_axi_lite_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_to_axi_lite_bridge/b_valid
add wave -noupdate -group soc_interconnect_wrap -group axi_to_axi_lite_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_to_axi_lite_bridge/b_ready
add wave -noupdate -group soc_interconnect_wrap -group axi_to_axi_lite_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_to_axi_lite_bridge/ar_id
add wave -noupdate -group soc_interconnect_wrap -group axi_to_axi_lite_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_to_axi_lite_bridge/ar_addr
add wave -noupdate -group soc_interconnect_wrap -group axi_to_axi_lite_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_to_axi_lite_bridge/ar_len
add wave -noupdate -group soc_interconnect_wrap -group axi_to_axi_lite_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_to_axi_lite_bridge/ar_size
add wave -noupdate -group soc_interconnect_wrap -group axi_to_axi_lite_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_to_axi_lite_bridge/ar_burst
add wave -noupdate -group soc_interconnect_wrap -group axi_to_axi_lite_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_to_axi_lite_bridge/ar_lock
add wave -noupdate -group soc_interconnect_wrap -group axi_to_axi_lite_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_to_axi_lite_bridge/ar_cache
add wave -noupdate -group soc_interconnect_wrap -group axi_to_axi_lite_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_to_axi_lite_bridge/ar_prot
add wave -noupdate -group soc_interconnect_wrap -group axi_to_axi_lite_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_to_axi_lite_bridge/ar_qos
add wave -noupdate -group soc_interconnect_wrap -group axi_to_axi_lite_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_to_axi_lite_bridge/ar_region
add wave -noupdate -group soc_interconnect_wrap -group axi_to_axi_lite_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_to_axi_lite_bridge/ar_user
add wave -noupdate -group soc_interconnect_wrap -group axi_to_axi_lite_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_to_axi_lite_bridge/ar_valid
add wave -noupdate -group soc_interconnect_wrap -group axi_to_axi_lite_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_to_axi_lite_bridge/ar_ready
add wave -noupdate -group soc_interconnect_wrap -group axi_to_axi_lite_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_to_axi_lite_bridge/r_id
add wave -noupdate -group soc_interconnect_wrap -group axi_to_axi_lite_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_to_axi_lite_bridge/r_data
add wave -noupdate -group soc_interconnect_wrap -group axi_to_axi_lite_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_to_axi_lite_bridge/r_resp
add wave -noupdate -group soc_interconnect_wrap -group axi_to_axi_lite_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_to_axi_lite_bridge/r_last
add wave -noupdate -group soc_interconnect_wrap -group axi_to_axi_lite_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_to_axi_lite_bridge/r_user
add wave -noupdate -group soc_interconnect_wrap -group axi_to_axi_lite_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_to_axi_lite_bridge/r_valid
add wave -noupdate -group soc_interconnect_wrap -group axi_to_axi_lite_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_to_axi_lite_bridge/r_ready
add wave -noupdate -group soc_interconnect_wrap -group axi_lite_to_apb_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_lite_to_apb_bridge/AXI_ADDR_WIDTH
add wave -noupdate -group soc_interconnect_wrap -group axi_lite_to_apb_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_lite_to_apb_bridge/AXI_DATA_WIDTH
add wave -noupdate -group soc_interconnect_wrap -group axi_lite_to_apb_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_lite_to_apb_bridge/AXI_STRB_WIDTH
add wave -noupdate -group soc_interconnect_wrap -group axi_lite_to_apb_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_lite_to_apb_bridge/aw_addr
add wave -noupdate -group soc_interconnect_wrap -group axi_lite_to_apb_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_lite_to_apb_bridge/aw_prot
add wave -noupdate -group soc_interconnect_wrap -group axi_lite_to_apb_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_lite_to_apb_bridge/aw_valid
add wave -noupdate -group soc_interconnect_wrap -group axi_lite_to_apb_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_lite_to_apb_bridge/aw_ready
add wave -noupdate -group soc_interconnect_wrap -group axi_lite_to_apb_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_lite_to_apb_bridge/w_data
add wave -noupdate -group soc_interconnect_wrap -group axi_lite_to_apb_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_lite_to_apb_bridge/w_strb
add wave -noupdate -group soc_interconnect_wrap -group axi_lite_to_apb_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_lite_to_apb_bridge/w_valid
add wave -noupdate -group soc_interconnect_wrap -group axi_lite_to_apb_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_lite_to_apb_bridge/w_ready
add wave -noupdate -group soc_interconnect_wrap -group axi_lite_to_apb_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_lite_to_apb_bridge/b_resp
add wave -noupdate -group soc_interconnect_wrap -group axi_lite_to_apb_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_lite_to_apb_bridge/b_valid
add wave -noupdate -group soc_interconnect_wrap -group axi_lite_to_apb_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_lite_to_apb_bridge/b_ready
add wave -noupdate -group soc_interconnect_wrap -group axi_lite_to_apb_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_lite_to_apb_bridge/ar_addr
add wave -noupdate -group soc_interconnect_wrap -group axi_lite_to_apb_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_lite_to_apb_bridge/ar_prot
add wave -noupdate -group soc_interconnect_wrap -group axi_lite_to_apb_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_lite_to_apb_bridge/ar_valid
add wave -noupdate -group soc_interconnect_wrap -group axi_lite_to_apb_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_lite_to_apb_bridge/ar_ready
add wave -noupdate -group soc_interconnect_wrap -group axi_lite_to_apb_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_lite_to_apb_bridge/r_data
add wave -noupdate -group soc_interconnect_wrap -group axi_lite_to_apb_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_lite_to_apb_bridge/r_resp
add wave -noupdate -group soc_interconnect_wrap -group axi_lite_to_apb_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_lite_to_apb_bridge/r_valid
add wave -noupdate -group soc_interconnect_wrap -group axi_lite_to_apb_bridge /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_lite_to_apb_bridge/r_ready
add wave -noupdate -group soc_interconnect_wrap -group axi_bridge_2_interconnect0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_bridge_2_interconnect[0]/req}
add wave -noupdate -group soc_interconnect_wrap -group axi_bridge_2_interconnect0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_bridge_2_interconnect[0]/add}
add wave -noupdate -group soc_interconnect_wrap -group axi_bridge_2_interconnect0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_bridge_2_interconnect[0]/wen}
add wave -noupdate -group soc_interconnect_wrap -group axi_bridge_2_interconnect0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_bridge_2_interconnect[0]/wdata}
add wave -noupdate -group soc_interconnect_wrap -group axi_bridge_2_interconnect0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_bridge_2_interconnect[0]/be}
add wave -noupdate -group soc_interconnect_wrap -group axi_bridge_2_interconnect0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_bridge_2_interconnect[0]/gnt}
add wave -noupdate -group soc_interconnect_wrap -group axi_bridge_2_interconnect0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_bridge_2_interconnect[0]/r_opc}
add wave -noupdate -group soc_interconnect_wrap -group axi_bridge_2_interconnect0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_bridge_2_interconnect[0]/r_rdata}
add wave -noupdate -group soc_interconnect_wrap -group axi_bridge_2_interconnect0 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_bridge_2_interconnect[0]/r_valid}
add wave -noupdate -group soc_interconnect_wrap -group axi_bridge_2_interconnect1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_bridge_2_interconnect[1]/req}
add wave -noupdate -group soc_interconnect_wrap -group axi_bridge_2_interconnect1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_bridge_2_interconnect[1]/add}
add wave -noupdate -group soc_interconnect_wrap -group axi_bridge_2_interconnect1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_bridge_2_interconnect[1]/wen}
add wave -noupdate -group soc_interconnect_wrap -group axi_bridge_2_interconnect1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_bridge_2_interconnect[1]/wdata}
add wave -noupdate -group soc_interconnect_wrap -group axi_bridge_2_interconnect1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_bridge_2_interconnect[1]/be}
add wave -noupdate -group soc_interconnect_wrap -group axi_bridge_2_interconnect1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_bridge_2_interconnect[1]/gnt}
add wave -noupdate -group soc_interconnect_wrap -group axi_bridge_2_interconnect1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_bridge_2_interconnect[1]/r_opc}
add wave -noupdate -group soc_interconnect_wrap -group axi_bridge_2_interconnect1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_bridge_2_interconnect[1]/r_rdata}
add wave -noupdate -group soc_interconnect_wrap -group axi_bridge_2_interconnect1 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_bridge_2_interconnect[1]/r_valid}
add wave -noupdate -group soc_interconnect_wrap -group axi_bridge_2_interconnect2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_bridge_2_interconnect[2]/req}
add wave -noupdate -group soc_interconnect_wrap -group axi_bridge_2_interconnect2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_bridge_2_interconnect[2]/add}
add wave -noupdate -group soc_interconnect_wrap -group axi_bridge_2_interconnect2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_bridge_2_interconnect[2]/wen}
add wave -noupdate -group soc_interconnect_wrap -group axi_bridge_2_interconnect2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_bridge_2_interconnect[2]/wdata}
add wave -noupdate -group soc_interconnect_wrap -group axi_bridge_2_interconnect2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_bridge_2_interconnect[2]/be}
add wave -noupdate -group soc_interconnect_wrap -group axi_bridge_2_interconnect2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_bridge_2_interconnect[2]/gnt}
add wave -noupdate -group soc_interconnect_wrap -group axi_bridge_2_interconnect2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_bridge_2_interconnect[2]/r_opc}
add wave -noupdate -group soc_interconnect_wrap -group axi_bridge_2_interconnect2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_bridge_2_interconnect[2]/r_rdata}
add wave -noupdate -group soc_interconnect_wrap -group axi_bridge_2_interconnect2 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_bridge_2_interconnect[2]/r_valid}
add wave -noupdate -group soc_interconnect_wrap -group axi_bridge_2_interconnect3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_bridge_2_interconnect[3]/req}
add wave -noupdate -group soc_interconnect_wrap -group axi_bridge_2_interconnect3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_bridge_2_interconnect[3]/add}
add wave -noupdate -group soc_interconnect_wrap -group axi_bridge_2_interconnect3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_bridge_2_interconnect[3]/wen}
add wave -noupdate -group soc_interconnect_wrap -group axi_bridge_2_interconnect3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_bridge_2_interconnect[3]/wdata}
add wave -noupdate -group soc_interconnect_wrap -group axi_bridge_2_interconnect3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_bridge_2_interconnect[3]/be}
add wave -noupdate -group soc_interconnect_wrap -group axi_bridge_2_interconnect3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_bridge_2_interconnect[3]/gnt}
add wave -noupdate -group soc_interconnect_wrap -group axi_bridge_2_interconnect3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_bridge_2_interconnect[3]/r_opc}
add wave -noupdate -group soc_interconnect_wrap -group axi_bridge_2_interconnect3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_bridge_2_interconnect[3]/r_rdata}
add wave -noupdate -group soc_interconnect_wrap -group axi_bridge_2_interconnect3 {/tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_soc_interconnect_wrap/axi_bridge_2_interconnect[3]/r_valid}
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ps} 0}
quietly wave cursor active 0
configure wave -namecolwidth 250
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ps} {859 ps}
