/* MTI_DPI */

/*
 * Copyright 2002-2017 Mentor Graphics Corporation.
 *
 * Note:
 *   This file is automatically generated.
 *   Please do not edit this file - you will lose your edits.
 *
 * Settings when this file was generated:
 *   PLATFORM = 'linux_x86_64'
 */
#ifndef INCLUDED_DPIHEADER
#define INCLUDED_DPIHEADER

#ifdef __cplusplus
#define DPI_LINK_DECL  extern "C" 
#else
#define DPI_LINK_DECL 
#endif

#include "svdpi.h"



DPI_LINK_DECL DPI_DLLESPEC
void*
dpi_config_get_config(
    void* config_handle,
    const char* path);

DPI_LINK_DECL DPI_DLLESPEC
void*
dpi_config_get_from_file(
    const char* path);

DPI_LINK_DECL DPI_DLLESPEC
int
dpi_config_get_int(
    void* config_handle);

DPI_LINK_DECL DPI_DLLESPEC
const char*
dpi_config_get_str(
    void* config_handle);

DPI_LINK_DECL DPI_DLLESPEC
void*
dpi_driver_get_comp_config(
    void* driver_handle,
    int index);

DPI_LINK_DECL DPI_DLLESPEC
void
dpi_driver_get_comp_itf_info(
    void* comp_handle,
    int index,
    int itf_index,
    const char** itf_name,
    const char** itf_type,
    int* itf_id,
    int* itf_sub_id);

DPI_LINK_DECL DPI_DLLESPEC
const char*
dpi_driver_get_comp_name(
    void* driver_handle,
    int index);

DPI_LINK_DECL DPI_DLLESPEC
int
dpi_driver_get_comp_nb_itf(
    void* comp_handle,
    int index);

DPI_LINK_DECL DPI_DLLESPEC
int
dpi_driver_get_nb_comp(
    void* driver_handle);

DPI_LINK_DECL DPI_DLLESPEC
void*
dpi_driver_set_config(
    void* config_handle);

DPI_LINK_DECL DPI_DLLESPEC
void*
dpi_model_load(
    void* comp_config);

DPI_LINK_DECL DPI_DLLESPEC
void*
dpi_qspim_bind(
    void* dpi_model,
    const char* name,
    int handle);

DPI_LINK_DECL DPI_DLLESPEC
void
dpi_qspim_cs_edge(
    void* handle,
    int64_t timestamp,
    svLogic csn);

DPI_LINK_DECL DPI_DLLESPEC
void
dpi_qspim_sck_edge(
    void* handle,
    int64_t timestamp,
    svLogic sck,
    svLogic data_0,
    svLogic data_1,
    svLogic data_2,
    svLogic data_3);

DPI_LINK_DECL void
dpi_print(
    void* handle,
    const char* msg);

DPI_LINK_DECL void
dpi_qspim_set_data(
    int handle,
    int data_0,
    int data_1,
    int data_2,
    int data_3);

#endif 
