// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package pulpissimo_padframe_all_pads_config_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 9;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    struct packed {
      logic [15:0] q;
    } hw_version;
    struct packed {
      logic [15:0] q;
    } padcount;
  } pulpissimo_padframe_all_pads_config_reg2hw_info_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io00_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io00_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io01_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io01_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io02_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io02_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io03_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io03_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io04_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io04_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io05_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io05_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io06_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io06_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io07_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io07_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io08_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io08_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io09_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io09_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io10_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io10_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io11_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io11_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io12_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io12_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io13_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io13_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io14_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io14_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io15_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io15_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io16_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io16_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io17_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io17_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io18_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io18_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io19_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io19_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io20_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io20_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io21_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io21_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io22_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io22_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io23_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io23_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io24_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io24_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io25_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io25_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io26_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io26_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io27_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io27_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io28_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io28_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io29_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io29_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io30_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io30_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } rx_en;
    struct packed {
      logic        q;
    } tx_en;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io31_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } pulpissimo_padframe_all_pads_config_reg2hw_pad_io31_mux_sel_reg_t;

  // Register -> HW type
  typedef struct packed {
    pulpissimo_padframe_all_pads_config_reg2hw_info_reg_t info; // [319:288]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io00_cfg_reg_t pad_io00_cfg; // [287:285]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io00_mux_sel_reg_t pad_io00_mux_sel; // [284:279]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io01_cfg_reg_t pad_io01_cfg; // [278:276]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io01_mux_sel_reg_t pad_io01_mux_sel; // [275:270]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io02_cfg_reg_t pad_io02_cfg; // [269:267]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io02_mux_sel_reg_t pad_io02_mux_sel; // [266:261]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io03_cfg_reg_t pad_io03_cfg; // [260:258]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io03_mux_sel_reg_t pad_io03_mux_sel; // [257:252]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io04_cfg_reg_t pad_io04_cfg; // [251:249]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io04_mux_sel_reg_t pad_io04_mux_sel; // [248:243]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io05_cfg_reg_t pad_io05_cfg; // [242:240]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io05_mux_sel_reg_t pad_io05_mux_sel; // [239:234]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io06_cfg_reg_t pad_io06_cfg; // [233:231]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io06_mux_sel_reg_t pad_io06_mux_sel; // [230:225]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io07_cfg_reg_t pad_io07_cfg; // [224:222]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io07_mux_sel_reg_t pad_io07_mux_sel; // [221:216]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io08_cfg_reg_t pad_io08_cfg; // [215:213]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io08_mux_sel_reg_t pad_io08_mux_sel; // [212:207]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io09_cfg_reg_t pad_io09_cfg; // [206:204]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io09_mux_sel_reg_t pad_io09_mux_sel; // [203:198]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io10_cfg_reg_t pad_io10_cfg; // [197:195]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io10_mux_sel_reg_t pad_io10_mux_sel; // [194:189]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io11_cfg_reg_t pad_io11_cfg; // [188:186]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io11_mux_sel_reg_t pad_io11_mux_sel; // [185:180]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io12_cfg_reg_t pad_io12_cfg; // [179:177]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io12_mux_sel_reg_t pad_io12_mux_sel; // [176:171]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io13_cfg_reg_t pad_io13_cfg; // [170:168]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io13_mux_sel_reg_t pad_io13_mux_sel; // [167:162]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io14_cfg_reg_t pad_io14_cfg; // [161:159]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io14_mux_sel_reg_t pad_io14_mux_sel; // [158:153]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io15_cfg_reg_t pad_io15_cfg; // [152:150]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io15_mux_sel_reg_t pad_io15_mux_sel; // [149:144]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io16_cfg_reg_t pad_io16_cfg; // [143:141]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io16_mux_sel_reg_t pad_io16_mux_sel; // [140:135]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io17_cfg_reg_t pad_io17_cfg; // [134:132]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io17_mux_sel_reg_t pad_io17_mux_sel; // [131:126]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io18_cfg_reg_t pad_io18_cfg; // [125:123]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io18_mux_sel_reg_t pad_io18_mux_sel; // [122:117]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io19_cfg_reg_t pad_io19_cfg; // [116:114]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io19_mux_sel_reg_t pad_io19_mux_sel; // [113:108]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io20_cfg_reg_t pad_io20_cfg; // [107:105]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io20_mux_sel_reg_t pad_io20_mux_sel; // [104:99]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io21_cfg_reg_t pad_io21_cfg; // [98:96]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io21_mux_sel_reg_t pad_io21_mux_sel; // [95:90]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io22_cfg_reg_t pad_io22_cfg; // [89:87]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io22_mux_sel_reg_t pad_io22_mux_sel; // [86:81]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io23_cfg_reg_t pad_io23_cfg; // [80:78]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io23_mux_sel_reg_t pad_io23_mux_sel; // [77:72]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io24_cfg_reg_t pad_io24_cfg; // [71:69]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io24_mux_sel_reg_t pad_io24_mux_sel; // [68:63]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io25_cfg_reg_t pad_io25_cfg; // [62:60]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io25_mux_sel_reg_t pad_io25_mux_sel; // [59:54]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io26_cfg_reg_t pad_io26_cfg; // [53:51]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io26_mux_sel_reg_t pad_io26_mux_sel; // [50:45]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io27_cfg_reg_t pad_io27_cfg; // [44:42]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io27_mux_sel_reg_t pad_io27_mux_sel; // [41:36]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io28_cfg_reg_t pad_io28_cfg; // [35:33]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io28_mux_sel_reg_t pad_io28_mux_sel; // [32:27]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io29_cfg_reg_t pad_io29_cfg; // [26:24]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io29_mux_sel_reg_t pad_io29_mux_sel; // [23:18]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io30_cfg_reg_t pad_io30_cfg; // [17:15]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io30_mux_sel_reg_t pad_io30_mux_sel; // [14:9]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io31_cfg_reg_t pad_io31_cfg; // [8:6]
    pulpissimo_padframe_all_pads_config_reg2hw_pad_io31_mux_sel_reg_t pad_io31_mux_sel; // [5:0]
  } pulpissimo_padframe_all_pads_config_reg2hw_t;

  // Register offsets
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_INFO_OFFSET = 9'h 0;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO00_CFG_OFFSET = 9'h 4;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO00_MUX_SEL_OFFSET = 9'h 8;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO01_CFG_OFFSET = 9'h c;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO01_MUX_SEL_OFFSET = 9'h 10;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO02_CFG_OFFSET = 9'h 14;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO02_MUX_SEL_OFFSET = 9'h 18;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO03_CFG_OFFSET = 9'h 1c;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO03_MUX_SEL_OFFSET = 9'h 20;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO04_CFG_OFFSET = 9'h 24;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO04_MUX_SEL_OFFSET = 9'h 28;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO05_CFG_OFFSET = 9'h 2c;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO05_MUX_SEL_OFFSET = 9'h 30;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO06_CFG_OFFSET = 9'h 34;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO06_MUX_SEL_OFFSET = 9'h 38;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO07_CFG_OFFSET = 9'h 3c;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO07_MUX_SEL_OFFSET = 9'h 40;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO08_CFG_OFFSET = 9'h 44;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO08_MUX_SEL_OFFSET = 9'h 48;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO09_CFG_OFFSET = 9'h 4c;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO09_MUX_SEL_OFFSET = 9'h 50;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO10_CFG_OFFSET = 9'h 54;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO10_MUX_SEL_OFFSET = 9'h 58;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO11_CFG_OFFSET = 9'h 5c;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO11_MUX_SEL_OFFSET = 9'h 60;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO12_CFG_OFFSET = 9'h 64;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO12_MUX_SEL_OFFSET = 9'h 68;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO13_CFG_OFFSET = 9'h 6c;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO13_MUX_SEL_OFFSET = 9'h 70;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO14_CFG_OFFSET = 9'h 74;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO14_MUX_SEL_OFFSET = 9'h 78;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO15_CFG_OFFSET = 9'h 7c;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO15_MUX_SEL_OFFSET = 9'h 80;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO16_CFG_OFFSET = 9'h 84;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO16_MUX_SEL_OFFSET = 9'h 88;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO17_CFG_OFFSET = 9'h 8c;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO17_MUX_SEL_OFFSET = 9'h 90;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO18_CFG_OFFSET = 9'h 94;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO18_MUX_SEL_OFFSET = 9'h 98;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO19_CFG_OFFSET = 9'h 9c;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO19_MUX_SEL_OFFSET = 9'h a0;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO20_CFG_OFFSET = 9'h a4;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO20_MUX_SEL_OFFSET = 9'h a8;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO21_CFG_OFFSET = 9'h ac;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO21_MUX_SEL_OFFSET = 9'h b0;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO22_CFG_OFFSET = 9'h b4;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO22_MUX_SEL_OFFSET = 9'h b8;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO23_CFG_OFFSET = 9'h bc;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO23_MUX_SEL_OFFSET = 9'h c0;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO24_CFG_OFFSET = 9'h c4;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO24_MUX_SEL_OFFSET = 9'h c8;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO25_CFG_OFFSET = 9'h cc;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO25_MUX_SEL_OFFSET = 9'h d0;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO26_CFG_OFFSET = 9'h d4;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO26_MUX_SEL_OFFSET = 9'h d8;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO27_CFG_OFFSET = 9'h dc;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO27_MUX_SEL_OFFSET = 9'h e0;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO28_CFG_OFFSET = 9'h e4;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO28_MUX_SEL_OFFSET = 9'h e8;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO29_CFG_OFFSET = 9'h ec;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO29_MUX_SEL_OFFSET = 9'h f0;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO30_CFG_OFFSET = 9'h f4;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO30_MUX_SEL_OFFSET = 9'h f8;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO31_CFG_OFFSET = 9'h fc;
  parameter logic [BlockAw-1:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO31_MUX_SEL_OFFSET = 9'h 100;

  // Register index
  typedef enum int {
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_INFO,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO00_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO00_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO01_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO01_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO02_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO02_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO03_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO03_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO04_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO04_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO05_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO05_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO06_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO06_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO07_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO07_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO08_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO08_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO09_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO09_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO10_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO10_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO11_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO11_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO12_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO12_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO13_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO13_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO14_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO14_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO15_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO15_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO16_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO16_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO17_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO17_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO18_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO18_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO19_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO19_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO20_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO20_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO21_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO21_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO22_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO22_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO23_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO23_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO24_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO24_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO25_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO25_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO26_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO26_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO27_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO27_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO28_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO28_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO29_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO29_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO30_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO30_MUX_SEL,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO31_CFG,
    PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO31_MUX_SEL
  } pulpissimo_padframe_all_pads_config_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PERMIT [65] = '{
    4'b 1111, // index[ 0] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_INFO
    4'b 0001, // index[ 1] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO00_CFG
    4'b 0001, // index[ 2] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO00_MUX_SEL
    4'b 0001, // index[ 3] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO01_CFG
    4'b 0001, // index[ 4] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO01_MUX_SEL
    4'b 0001, // index[ 5] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO02_CFG
    4'b 0001, // index[ 6] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO02_MUX_SEL
    4'b 0001, // index[ 7] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO03_CFG
    4'b 0001, // index[ 8] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO03_MUX_SEL
    4'b 0001, // index[ 9] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO04_CFG
    4'b 0001, // index[10] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO04_MUX_SEL
    4'b 0001, // index[11] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO05_CFG
    4'b 0001, // index[12] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO05_MUX_SEL
    4'b 0001, // index[13] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO06_CFG
    4'b 0001, // index[14] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO06_MUX_SEL
    4'b 0001, // index[15] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO07_CFG
    4'b 0001, // index[16] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO07_MUX_SEL
    4'b 0001, // index[17] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO08_CFG
    4'b 0001, // index[18] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO08_MUX_SEL
    4'b 0001, // index[19] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO09_CFG
    4'b 0001, // index[20] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO09_MUX_SEL
    4'b 0001, // index[21] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO10_CFG
    4'b 0001, // index[22] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO10_MUX_SEL
    4'b 0001, // index[23] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO11_CFG
    4'b 0001, // index[24] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO11_MUX_SEL
    4'b 0001, // index[25] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO12_CFG
    4'b 0001, // index[26] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO12_MUX_SEL
    4'b 0001, // index[27] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO13_CFG
    4'b 0001, // index[28] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO13_MUX_SEL
    4'b 0001, // index[29] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO14_CFG
    4'b 0001, // index[30] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO14_MUX_SEL
    4'b 0001, // index[31] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO15_CFG
    4'b 0001, // index[32] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO15_MUX_SEL
    4'b 0001, // index[33] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO16_CFG
    4'b 0001, // index[34] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO16_MUX_SEL
    4'b 0001, // index[35] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO17_CFG
    4'b 0001, // index[36] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO17_MUX_SEL
    4'b 0001, // index[37] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO18_CFG
    4'b 0001, // index[38] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO18_MUX_SEL
    4'b 0001, // index[39] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO19_CFG
    4'b 0001, // index[40] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO19_MUX_SEL
    4'b 0001, // index[41] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO20_CFG
    4'b 0001, // index[42] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO20_MUX_SEL
    4'b 0001, // index[43] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO21_CFG
    4'b 0001, // index[44] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO21_MUX_SEL
    4'b 0001, // index[45] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO22_CFG
    4'b 0001, // index[46] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO22_MUX_SEL
    4'b 0001, // index[47] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO23_CFG
    4'b 0001, // index[48] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO23_MUX_SEL
    4'b 0001, // index[49] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO24_CFG
    4'b 0001, // index[50] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO24_MUX_SEL
    4'b 0001, // index[51] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO25_CFG
    4'b 0001, // index[52] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO25_MUX_SEL
    4'b 0001, // index[53] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO26_CFG
    4'b 0001, // index[54] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO26_MUX_SEL
    4'b 0001, // index[55] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO27_CFG
    4'b 0001, // index[56] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO27_MUX_SEL
    4'b 0001, // index[57] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO28_CFG
    4'b 0001, // index[58] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO28_MUX_SEL
    4'b 0001, // index[59] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO29_CFG
    4'b 0001, // index[60] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO29_MUX_SEL
    4'b 0001, // index[61] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO30_CFG
    4'b 0001, // index[62] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO30_MUX_SEL
    4'b 0001, // index[63] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO31_CFG
    4'b 0001  // index[64] PULPISSIMO_PADFRAME_ALL_PADS_CONFIG_PAD_IO31_MUX_SEL
  };

endpackage

