add_files -norecurse -scan_for_includes $SRC_SOC_INTERCONNECT
add_files -norecurse -scan_for_includes $SRC_ADV_DBG_IF
add_files -norecurse -scan_for_includes $SRC_APB2PER
add_files -norecurse -scan_for_includes $SRC_APB_ADV_TIMER
add_files -norecurse -scan_for_includes $SRC_APB_FLL_IF
add_files -norecurse -scan_for_includes $SRC_APB_GPIO
add_files -norecurse -scan_for_includes $SRC_APB_NODE
add_files -norecurse -scan_for_includes $SRC_APB_INTERRUPT_CNTRL
add_files -norecurse -scan_for_includes $SRC_AXI_NODE
add_files -norecurse -scan_for_includes $SRC_AXI_SLICE
add_files -norecurse -scan_for_includes $SRC_AXI_SLICE_DC
add_files -norecurse -scan_for_includes $SRC_TIMER_UNIT
add_files -norecurse -scan_for_includes $SRC_COMMON_CELLS_ALL
add_files -norecurse -scan_for_includes $SRC_FPU_NEW
add_files -norecurse -scan_for_includes $SRC_FPU_DIV_SQRT_MVP
add_files -norecurse -scan_for_includes $SRC_JTAG_PULP
add_files -norecurse -scan_for_includes $SRC_RISCV
add_files -norecurse -scan_for_includes $SRC_RISCV_DBG
add_files -norecurse -scan_for_includes $SRC_RISCV_REGFILE_FPGA
add_files -norecurse -scan_for_includes $SRC_ZERORISCY
add_files -norecurse -scan_for_includes $SRC_ZERORISCY_REGFILE_FPGA
add_files -norecurse -scan_for_includes $SRC_SCM_FPGA
add_files -norecurse -scan_for_includes $SRC_TECH_CELLS_FPGA
add_files -norecurse -scan_for_includes $SRC_UDMA_CORE
add_files -norecurse -scan_for_includes $SRC_UDMA_UART
add_files -norecurse -scan_for_includes $SRC_UDMA_I2C
add_files -norecurse -scan_for_includes $SRC_UDMA_I2S
add_files -norecurse -scan_for_includes $SRC_UDMA_QSPI
add_files -norecurse -scan_for_includes $SRC_UDMA_SDIO
add_files -norecurse -scan_for_includes $SRC_UDMA_CAMERA
add_files -norecurse -scan_for_includes $SRC_UDMA_EXTERNAL_PER
add_files -norecurse -scan_for_includes $SRC_UDMA_FILTER
add_files -norecurse -scan_for_includes $SRC_HWPE_CTRL
add_files -norecurse -scan_for_includes $SRC_HWPE_STREAM
add_files -norecurse -scan_for_includes $SRC_HW_MAC_ENGINE
add_files -norecurse -scan_for_includes $SRC_PULP_SOC
add_files -norecurse -scan_for_includes $SRC_UDMA_SUBSYSTEM
add_files -norecurse -scan_for_includes $SRC_FC
add_files -norecurse -scan_for_includes $SRC_COMPONENTS
