/*
 * Copyright (C) 2018 GreenWaves Technologies
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef __ARCHI_LNT_CSI2_V1_H__
#define __ARCHI_LNT_CSI2_V1_H__

// CSI2 Registers offset definition
#define APB_CSI2_CFG_OFFSET                          (0x60 << 2)
#define APB_CSI2_ERR_MSB1_OFFSET                     (0x61 << 2)
#define APB_CSI2_ERR_MSB_OFFSET                      (0x62 << 2)
#define APB_CSI2_ERR_LSB_OFFSET                      (0x63 << 2)
#define APB_CSI2_HS_RX_TIMEOUT_MSB2_OFFSET           (0x64 << 2)
#define APB_CSI2_HS_RX_TIMEOUT_MSB1_OFFSET           (0x65 << 2)
#define APB_CSI2_HS_RX_TIMEOUT_LSB_OFFSET            (0x66 << 2)
#define APB_CSI2_VCCFG_OFFSET                        (0x67 << 2)
#define APB_CSI2_POLARITY_OFFSET                     (0x68 << 2)
#define APB_CSI2_CCI_ADDR_OFFSET                     (0x69 << 2)
#define APB_CSI2_CCI_WR_DATA_OFFSET                  (0x6a << 2)
#define APB_CSI2_CCI_RD_DATA_OFFSET                  (0x6b << 2)
#define APB_CSI2_CCI_READ_WRITE_OFFSET               (0x6c << 2)
#define APB_CSI2_CCI_STATUS_OFFSET                   (0x6d << 2)
#define APB_CSI2_CCI_DEVICE_ADDR_OFFSET              (0x6e << 2)
#define APB_CSI2_ULPS_STATUS_OFFSET                  (0x6f << 2)

// CSI2 Registers bitfields offset, mask, value definition
#define APB_CSI2_CFG_LANE_NB_BIT                   				(0)
#define APB_CSI2_CFG_LANE_NB_BITS                  				(2)
#define APB_CSI2_CFG_LANE_NB_MASK                  				ARCHI_REG_MASK(APB_CSI2_CFG_LANE_NB_BIT,                  APB_CSI2_CFG_LANE_NB_BITS)
#define APB_CSI2_CFG_LANE_NB_2                     				(1<<APB_CSI2_CFG_LANE_NB_BIT)
#define APB_CSI2_CFG_LANE_NB_4                     				(3<<APB_CSI2_CFG_LANE_NB_BIT)

#define APB_CSI2_ERR_MSB1_CRC_ERROR_VC3_BIT        				(0)
#define APB_CSI2_ERR_MSB1_CRC_ERROR_VC3_BITS       				(1)
#define APB_CSI2_ERR_MSB1_CRC_ERROR_VC3_MASK       				ARCHI_REG_MASK(APB_CSI2_ERR_MSB1_CRC_ERROR_VC3_BIT,       APB_CSI2_ERR_MSB1_CRC_ERROR_VC3_BITS)
#define APB_CSI2_ERR_MSB1_CRC_ERROR_VC3            				(1<<APB_CSI2_ERR_MSB1_CRC_ERROR_VC3_BIT)

#define APB_CSI2_ERR_MSB1_ESC_ERROR_BIT            				(1)
#define APB_CSI2_ERR_MSB1_ESC_ERROR_BITS           				(1)
#define APB_CSI2_ERR_MSB1_ESC_ERROR_MASK           				ARCHI_REG_MASK(APB_CSI2_ERR_MSB1_ESC_ERROR_BIT,           APB_CSI2_ERR_MSB1_ESC_ERROR_BITS)
#define APB_CSI2_ERR_MSB1_ESC_ERROR                				(1<<APB_CSI2_ERR_MSB1_ESC_ERROR_BIT)

#define APB_CSI2_ERR_MSB_INVLD_PKT_LEN_BIT         				(0)
#define APB_CSI2_ERR_MSB_INVLD_PKT_LEN_BITS        				(1)
#define APB_CSI2_ERR_MSB_INVLD_PKT_LEN_MASK        				ARCHI_REG_MASK(APB_CSI2_ERR_MSB_INVLD_PKT_LEN_BIT,        APB_CSI2_ERR_MSB_INVLD_PKT_LEN_BITS)
#define APB_CSI2_ERR_MSB_INVLD_PKT_LEN             				(1<<APB_CSI2_ERR_MSB_INVLD_PKT_LEN_BIT)

#define APB_CSI2_ERR_MSB_FRAME_SYNC_ERR_BIT        				(1)
#define APB_CSI2_ERR_MSB_FRAME_SYNC_ERR_BITS       				(1)
#define APB_CSI2_ERR_MSB_FRAME_SYNC_ERR_MASK       				ARCHI_REG_MASK(APB_CSI2_ERR_MSB_FRAME_SYNC_ERR_BIT,       APB_CSI2_ERR_MSB_FRAME_SYNC_ERR_BITS)
#define APB_CSI2_ERR_MSB_FRAME_SYNC_ERR            				(1<<APB_CSI2_ERR_MSB_FRAME_SYNC_ERR_BIT)

#define APB_CSI2_ERR_MSB_ECC_NO_ERR_BIT            				(2)
#define APB_CSI2_ERR_MSB_ECC_NO_ERR_BITS           				(1)
#define APB_CSI2_ERR_MSB_ECC_NO_ERR_MASK           				ARCHI_REG_MASK(APB_CSI2_ERR_MSB_ECC_NO_ERR_BIT,           APB_CSI2_ERR_MSB_ECC_NO_ERR_BITS)
#define APB_CSI2_ERR_MSB_ECC_NO_ERR                				(1<<APB_CSI2_ERR_MSB_ECC_NO_ERR_BIT)

#define APB_CSI2_ERR_MSB_ECC_BIT_ERR_BIT           				(3)
#define APB_CSI2_ERR_MSB_ECC_BIT_ERR_BITS          				(1)
#define APB_CSI2_ERR_MSB_ECC_BIT_ERR_MASK          				ARCHI_REG_MASK(APB_CSI2_ERR_MSB_ECC_BIT_ERR_BIT,          APB_CSI2_ERR_MSB_ECC_BIT_ERR_BITS)
#define APB_CSI2_ERR_MSB_ECC_BIT_ERR               				(1<<APB_CSI2_ERR_MSB_ECC_BIT_ERR_BIT)

#define APB_CSI2_ERR_MSB_ERR_FRAME_DATA_BIT        				(4)
#define APB_CSI2_ERR_MSB_ERR_FRAME_DATA_BITS       				(1)
#define APB_CSI2_ERR_MSB_ERR_FRAME_DATA_MASK       				ARCHI_REG_MASK(APB_CSI2_ERR_MSB_ERR_FRAME_DATA_BIT,       APB_CSI2_ERR_MSB_ERR_FRAME_DATA_BITS)
#define APB_CSI2_ERR_MSB_ERR_FRAME_DATA            				(1<<APB_CSI2_ERR_MSB_ERR_FRAME_DATA_BIT)

#define APB_CSI2_ERR_MSB_HS_RX_TO_ERR_BIT          				(5)
#define APB_CSI2_ERR_MSB_HS_RX_TO_ERR_BITS         				(1)
#define APB_CSI2_ERR_MSB_HS_RX_TO_ERR_MASK         				ARCHI_REG_MASK(APB_CSI2_ERR_MSB_HS_RX_TO_ERR_BIT,         APB_CSI2_ERR_MSB_HS_RX_TO_ERR_BITS)
#define APB_CSI2_ERR_MSB_HS_RX_TO_ERR              				(1<<APB_CSI2_ERR_MSB_HS_RX_TO_ERR_BIT)

#define APB_CSI2_ERR_MSB_CRC_ERROR_VC1_BIT         				(6)
#define APB_CSI2_ERR_MSB_CRC_ERROR_VC1_BITS        				(1)
#define APB_CSI2_ERR_MSB_CRC_ERROR_VC1_MASK        				ARCHI_REG_MASK(APB_CSI2_ERR_MSB_CRC_ERROR_VC1_BIT,        APB_CSI2_ERR_MSB_CRC_ERROR_VC1_BITS)
#define APB_CSI2_ERR_MSB_CRC_ERROR_VC1             				(1<<APB_CSI2_ERR_MSB_CRC_ERROR_VC1_BIT)

#define APB_CSI2_ERR_MSB_CRC_ERROR_VC2_BIT         				(7)
#define APB_CSI2_ERR_MSB_CRC_ERROR_VC2_BITS        				(1)
#define APB_CSI2_ERR_MSB_CRC_ERROR_VC2_MASK        				ARCHI_REG_MASK(APB_CSI2_ERR_MSB_CRC_ERROR_VC2_BIT,        APB_CSI2_ERR_MSB_CRC_ERROR_VC2_BITS)
#define APB_CSI2_ERR_MSB_CRC_ERROR_VC2             				(1<<APB_CSI2_ERR_MSB_CRC_ERROR_VC2_BIT)

#define APB_CSI2_ERR_LSB_SOT_ERROR_BIT             				(0)
#define APB_CSI2_ERR_LSB_SOT_ERROR_BITS            				(1)
#define APB_CSI2_ERR_LSB_SOT_ERROR_MASK            				ARCHI_REG_MASK(APB_CSI2_ERR_LSB_SOT_ERROR_BIT,            APB_CSI2_ERR_LSB_SOT_ERROR_BITS)
#define APB_CSI2_ERR_LSB_SOT_ERROR                 				(1<<APB_CSI2_ERR_LSB_SOT_ERROR_BIT)

#define APB_CSI2_ERR_LSB_SOT_SYNC_ERROR_BIT        				(1)
#define APB_CSI2_ERR_LSB_SOT_SYNC_ERROR_BITS       				(1)
#define APB_CSI2_ERR_LSB_SOT_SYNC_ERROR_MASK       				ARCHI_REG_MASK(APB_CSI2_ERR_LSB_SOT_SYNC_ERROR_BIT,       APB_CSI2_ERR_LSB_SOT_SYNC_ERROR_BITS)
#define APB_CSI2_ERR_LSB_SOT_SYNC_ERROR            				(1<<APB_CSI2_ERR_LSB_SOT_SYNC_ERROR_BIT)

#define APB_CSI2_ERR_LSB_FALSE_CTRL_BIT            				(2)
#define APB_CSI2_ERR_LSB_FALSE_CTRL_BITS           				(1)
#define APB_CSI2_ERR_LSB_FALSE_CTRL_MASK           				ARCHI_REG_MASK(APB_CSI2_ERR_LSB_FALSE_CTRL_BIT,           APB_CSI2_ERR_LSB_FALSE_CTRL_BITS)
#define APB_CSI2_ERR_LSB_FALSE_CTRL                				(1<<APB_CSI2_ERR_LSB_FALSE_CTRL_BIT)

#define APB_CSI2_ERR_LSB_ECC_ERR_SINGLE_BIT        				(3)
#define APB_CSI2_ERR_LSB_ECC_ERR_SINGLE_BITS       				(1)
#define APB_CSI2_ERR_LSB_ECC_ERR_SINGLE_MASK       				ARCHI_REG_MASK(APB_CSI2_ERR_LSB_ECC_ERR_SINGLE_BIT,       APB_CSI2_ERR_LSB_ECC_ERR_SINGLE_BITS)
#define APB_CSI2_ERR_LSB_ECC_ERR_SINGLE            				(1<<APB_CSI2_ERR_LSB_ECC_ERR_SINGLE_BIT)

#define APB_CSI2_ERR_LSB_ECC_ERR_MULT_BIT          				(4)
#define APB_CSI2_ERR_LSB_ECC_ERR_MULT_BITS         				(1)
#define APB_CSI2_ERR_LSB_ECC_ERR_MULT_MASK         				ARCHI_REG_MASK(APB_CSI2_ERR_LSB_ECC_ERR_MULT_BIT,         APB_CSI2_ERR_LSB_ECC_ERR_MULT_BITS)
#define APB_CSI2_ERR_LSB_ECC_ERR_MULT              				(1<<APB_CSI2_ERR_LSB_ECC_ERR_MULT_BIT)

#define APB_CSI2_ERR_LSB_CRC_ERROR_VC0_BIT         				(5)
#define APB_CSI2_ERR_LSB_CRC_ERROR_VC0_BITS        				(1)
#define APB_CSI2_ERR_LSB_CRC_ERROR_VC0_MASK        				ARCHI_REG_MASK(APB_CSI2_ERR_LSB_CRC_ERROR_VC0_BIT,        APB_CSI2_ERR_LSB_CRC_ERROR_VC0_BITS)
#define APB_CSI2_ERR_LSB_CRC_ERROR_VC0             				(1<<APB_CSI2_ERR_LSB_CRC_ERROR_VC0_BIT)

#define APB_CSI2_ERR_LSB_INVLD_DATA_TYPE_BIT       				(6)
#define APB_CSI2_ERR_LSB_INVLD_DATA_TYPE_BITS      				(1)
#define APB_CSI2_ERR_LSB_INVLD_DATA_TYPE_MASK      				ARCHI_REG_MASK(APB_CSI2_ERR_LSB_INVLD_DATA_TYPE_BIT,      APB_CSI2_ERR_LSB_INVLD_DATA_TYPE_BITS)
#define APB_CSI2_ERR_LSB_INVLD_DATA_TYPE           				(1<<APB_CSI2_ERR_LSB_INVLD_DATA_TYPE_BIT)

#define APB_CSI2_ERR_LSB_INVLD_VC_ID_BIT           				(7)
#define APB_CSI2_ERR_LSB_INVLD_VC_ID_BITS          				(1)
#define APB_CSI2_ERR_LSB_INVLD_VC_ID_MASK          				ARCHI_REG_MASK(APB_CSI2_ERR_LSB_INVLD_VC_ID_BIT,          APB_CSI2_ERR_LSB_INVLD_VC_ID_BITS)
#define APB_CSI2_ERR_LSB_INVLD_VC_ID               				(1<<APB_CSI2_ERR_LSB_INVLD_VC_ID_BIT)

#define APB_CSI2_HS_RX_TIMEOUT_MSB2_BIT            				(0)
#define APB_CSI2_HS_RX_TIMEOUT_MSB2_BITS           				(8)
#define APB_CSI2_HS_RX_TIMEOUT_MSB2_MASK           				ARCHI_REG_MASK(APB_CSI2_HS_RX_TIMEOUT_MSB2_BIT,           APB_CSI2_HS_RX_TIMEOUT_MSB2_BITS)
#define APB_CSI2_HS_RX_TIMEOUT_MSB2(val)           				(val<<APB_CSI2_HS_RX_TIMEOUT_MSB2_BIT)

#define APB_CSI2_HS_RX_TIMEOUT_MSB1_BIT            				(0)
#define APB_CSI2_HS_RX_TIMEOUT_MSB1_BITS           				(8)
#define APB_CSI2_HS_RX_TIMEOUT_MSB1_MASK           				ARCHI_REG_MASK(APB_CSI2_HS_RX_TIMEOUT_MSB1_BIT,           APB_CSI2_HS_RX_TIMEOUT_MSB1_BITS)
#define APB_CSI2_HS_RX_TIMEOUT_MSB1(val)           				(val<<APB_CSI2_HS_RX_TIMEOUT_MSB1_BIT)

#define APB_CSI2_HS_RX_TIMEOUT_LSB_BIT             				(0)
#define APB_CSI2_HS_RX_TIMEOUT_LSB_BITS            				(8)
#define APB_CSI2_HS_RX_TIMEOUT_LSB_MASK            				ARCHI_REG_MASK(APB_CSI2_HS_RX_TIMEOUT_LSB_BIT,            APB_CSI2_HS_RX_TIMEOUT_LSB_BITS)
#define APB_CSI2_HS_RX_TIMEOUT_LSB(val)            				(val<<APB_CSI2_HS_RX_TIMEOUT_LSB_BIT)

#define APB_CSI2_VCCFG_BIT                         				(0)
#define APB_CSI2_VCCFG_BITS                        				(4)
#define APB_CSI2_VCCFG_MASK                        				ARCHI_REG_MASK(APB_CSI2_VCCFG_BIT,                        APB_CSI2_VCCFG_BITS)
#define APB_CSI2_VCCFG(val)                        				(val<<APB_CSI2_VCCFG_BIT)

#define APB_CSI2_POLARITY_VSYNC_BIT                				(0)
#define APB_CSI2_POLARITY_VSYNC_BITS               				(1)
#define APB_CSI2_POLARITY_VSYNC_MASK               				ARCHI_REG_MASK(APB_CSI2_POLARITY_VSYNC_BIT,               APB_CSI2_POLARITY_VSYNC_BITS)
#define APB_CSI2_POLARITY_VSYNC_LOW                				(1<<APB_CSI2_POLARITY_VSYNC_BIT)
#define APB_CSI2_POLARITY_VSYNC_HIGH               				(0<<APB_CSI2_POLARITY_VSYNC_BIT)

#define APB_CSI2_POLARITY_HSYNC_BIT                				(1)
#define APB_CSI2_POLARITY_HSYNC_BITS               				(1)
#define APB_CSI2_POLARITY_HSYNC_MASK               				ARCHI_REG_MASK(APB_CSI2_POLARITY_HSYNC_BIT,               APB_CSI2_POLARITY_HSYNC_BITS)
#define APB_CSI2_POLARITY_HSYNC_LOW                				(1<<APB_CSI2_POLARITY_HSYNC_BIT)
#define APB_CSI2_POLARITY_HSYNC_HIGH               				(0<<APB_CSI2_POLARITY_HSYNC_BIT)

#define APB_CSI2_CCI_ADDRESS_BIT                   				(0)
#define APB_CSI2_CCI_ADDRESS_BITS                  				(8)
#define APB_CSI2_CCI_ADDRESS_MASK                  				ARCHI_REG_MASK(APB_CSI2_CCI_ADDRESS_BIT,                  APB_CSI2_CCI_ADDRESS_BITS)
#define APB_CSI2_CCI_ADDRESS(val)                  				(val<<APB_CSI2_CCI_ADDRESS_BIT)

#define APB_CSI2_CCI_WRITE_DATA_BIT                				(0)
#define APB_CSI2_CCI_WRITE_DATA_BITS               				(8)
#define APB_CSI2_CCI_WRITE_DATA_MASK               				ARCHI_REG_MASK(APB_CSI2_CCI_WRITE_DATA_BIT,               APB_CSI2_CCI_WRITE_DATA_BITS)
#define APB_CSI2_CCI_WRITE_DATA_(val)              				(val<<APB_CSI2_CCI_WRITE_DATA_BIT)

#define APB_CSI2_CCI_READ_DATA_BIT                 				(0)
#define APB_CSI2_CCI_READ_DATA_BITS                				(8)
#define APB_CSI2_CCI_READ_DATA_MASK                				ARCHI_REG_MASK(APB_CSI2_CCI_READ_DATA_BIT,                APB_CSI2_CCI_READ_DATA_BITS)
#define APB_CSI2_CCI_READ_DATA_(val)               				(val<<APB_CSI2_CCI_READ_DATA_BIT)

#define APB_CSI2_CCI_READ_WRITE_BYTE_BIT           				(0)
#define APB_CSI2_CCI_READ_WRITE_BYTE_BITS          				(7)
#define APB_CSI2_CCI_READ_WRITE_BYTE_MASK          				ARCHI_REG_MASK(APB_CSI2_CCI_READ_WRITE_BYTE_BIT,          APB_CSI2_CCI_READ_WRITE_BYTE_BITS)
#define APB_CSI2_CCI_READ_WRITE_BYTE_(val)         				(val<<APB_CSI2_CCI_READ_WRITE_BYTE_BIT)

#define APB_CSI2_CCI_READ_WRITE_WR_BIT             				(7)
#define APB_CSI2_CCI_READ_WRITE_WR_BITS            				(1)
#define APB_CSI2_CCI_READ_WRITE_WR_MASK            				ARCHI_REG_MASK(APB_CSI2_CCI_READ_WRITE_WR_BIT,            APB_CSI2_CCI_READ_WRITE_WR_BITS)
#define APB_CSI2_CCI_READ_WRITE_WR_1               				(1<<APB_CSI2_CCI_READ_WRITE_WR_BIT)
#define APB_CSI2_CCI_READ_WRITE_WR_0               				(0<<APB_CSI2_CCI_READ_WRITE_WR_BIT)

#define APB_CSI2_CCI_STATUS_RW_TRANSFER_DONE_BIT   				(0)
#define APB_CSI2_CCI_STATUS_RW_TRANSFER_DONE_BITS  				(1)
#define APB_CSI2_CCI_STATUS_RW_TRANSFER_DONE_MASK  				ARCHI_REG_MASK(APB_CSI2_CCI_STATUS_RW_TRANSFER_DONE_BIT,  APB_CSI2_CCI_STATUS_RW_TRANSFER_DONE_BITS)
#define APB_CSI2_CCI_STATUS_RW_TRANSFER_DONE       				(1<<APB_CSI2_CCI_STATUS_RW_TRANSFER_DONE_BIT)

#define APB_CSI2_CCI_STATUS_RD_DATA_AVAILABLE_BIT  				(1)
#define APB_CSI2_CCI_STATUS_RD_DATA_AVAILABLE_BITS 				(1)
#define APB_CSI2_CCI_STATUS_RD_DATA_AVAILABLE_MASK 				ARCHI_REG_MASK(APB_CSI2_CCI_STATUS_RD_DATA_AVAILABLE_BIT, APB_CSI2_CCI_STATUS_RD_DATA_AVAILABLE_BITS)
#define APB_CSI2_CCI_STATUS_RD_DATA_AVAILABLE      				(1<<APB_CSI2_CCI_STATUS_RD_DATA_AVAILABLE_BIT)

#define APB_CSI2_CCI_DEVICE_ADDRESS_BIT            				(0)
#define APB_CSI2_CCI_DEVICE_ADDRESS_BITS           				(7)
#define APB_CSI2_CCI_DEVICE_ADDRESS_MASK           				ARCHI_REG_MASK(APB_CSI2_CCI_DEVICE_ADDRESS_BIT,           APB_CSI2_CCI_DEVICE_ADDRESS_BITS)
#define APB_CSI2_CCI_DEVICE_ADDRESS_(val)          				(val<<APB_CSI2_CCI_DEVICE_ADDRESS_BIT)

#define APB_CSI2_ULPS_STATUS_LANE_0_BIT            				(0)
#define APB_CSI2_ULPS_STATUS_LANE_0_BITS           				(1)
#define APB_CSI2_ULPS_STATUS_LANE_0_MASK           				ARCHI_REG_MASK(APB_CSI2_ULPS_STATUS_LANE_0_BIT,           APB_CSI2_ULPS_STATUS_LANE_0_BITS)
#define APB_CSI2_ULPS_STATUS_LANE_0_ACTIVE         				(1<<APB_CSI2_ULPS_STATUS_LANE_0_BIT)

#define APB_CSI2_ULPS_STATUS_LANE_1_BIT            				(1)
#define APB_CSI2_ULPS_STATUS_LANE_1_BITS           				(1)
#define APB_CSI2_ULPS_STATUS_LANE_1_MASK           				ARCHI_REG_MASK(APB_CSI2_ULPS_STATUS_LANE_1_BIT,           APB_CSI2_ULPS_STATUS_LANE_1_BITS)
#define APB_CSI2_ULPS_STATUS_LANE_1_ACTIVE         				(1<<APB_CSI2_ULPS_STATUS_LANE_1_BIT)

#define APB_CSI2_ULPS_STATUS_LANE_2_BIT            				(2)
#define APB_CSI2_ULPS_STATUS_LANE_2_BITS           				(1)
#define APB_CSI2_ULPS_STATUS_LANE_2_MASK           				ARCHI_REG_MASK(APB_CSI2_ULPS_STATUS_LANE_2_BIT,           APB_CSI2_ULPS_STATUS_LANE_2_BITS)
#define APB_CSI2_ULPS_STATUS_LANE_2_ACTIVE         				(1<<APB_CSI2_ULPS_STATUS_LANE_2_BIT)

#define APB_CSI2_ULPS_STATUS_LANE_3_BIT            				(3)
#define APB_CSI2_ULPS_STATUS_LANE_3_BITS           				(1)
#define APB_CSI2_ULPS_STATUS_LANE_3_MASK           				ARCHI_REG_MASK(APB_CSI2_ULPS_STATUS_LANE_3_BIT,           APB_CSI2_ULPS_STATUS_LANE_3_BITS)
#define APB_CSI2_ULPS_STATUS_LANE_3_ACTIVE         				(1<<APB_CSI2_ULPS_STATUS_LANE_3_BIT)





// DPHY Registers offset definition
#define APB_CSI2_DPHY_LANE_ENABLE_OFFSET             (0x00 << 2)

//TODO
// #define APB_CSI2_DPHY_LANE_ENABLE_OFFSET             (0x0d << 2)
// #define APB_CSI2_DPHY_LANE_ENABLE_OFFSET             (0x0e << 2)
// #define APB_CSI2_DPHY_LANE_ENABLE_OFFSET             (0x0f << 2)

#define APB_CSI2_DPHY_RESET_DIG_LOGIC_OFFSET         (0x20 << 2)
#define APB_CSI2_DPHY_LANE_CK_CONT_MODE_OFFSET       (0x4a << 2)
#define APB_CSI2_DPHY_LANE_CK_HS_COUNTDOWN_OFFSET    (0x58 << 2)
#define APB_CSI2_DPHY_LANE_CK_RX_CALIB_ENABLE_OFFSET (0x5a << 2)
#define APB_CSI2_DPHY_LANE_0_HS_COUNTDOWN_OFFSET     (0x78 << 2)
#define APB_CSI2_DPHY_LANE_0_RX_CALIB_ENABLE_OFFSET  (0x7a << 2)
#define APB_CSI2_DPHY_LANE_1_HS_COUNTDOWN_OFFSET     (0x98 << 2)
#define APB_CSI2_DPHY_LANE_1_RX_CALIB_ENABLE_OFFSET  (0x9a << 2)

// DPHY Registers bitfields offset, mask, value definition
#define APB_CSI2_DPHY_ENABLE_LANE_0_BIT       				(2)
#define APB_CSI2_DPHY_ENABLE_LANE_0_BITS      				(1)
#define APB_CSI2_DPHY_ENABLE_LANE_0_MASK      				ARCHI_REG_MASK(APB_CSI2_DPHY_ENABLE_LANE_0_BIT,      APB_CSI2_DPHY_ENABLE_LANE_0_BITS)
#define APB_CSI2_DPHY_ENABLE_LANE_0_ENA       				(1<<APB_CSI2_DPHY_ENABLE_LANE_0_BIT)
#define APB_CSI2_DPHY_ENABLE_LANE_0_DIS       				(0<<APB_CSI2_DPHY_ENABLE_LANE_0_BIT)

#define APB_CSI2_DPHY_ENABLE_LANE_1_BIT       				(3)
#define APB_CSI2_DPHY_ENABLE_LANE_1_BITS      				(1)
#define APB_CSI2_DPHY_ENABLE_LANE_1_MASK      				ARCHI_REG_MASK(APB_CSI2_DPHY_ENABLE_LANE_1_BIT,      APB_CSI2_DPHY_ENABLE_LANE_1_BITS)
#define APB_CSI2_DPHY_ENABLE_LANE_1_ENA       				(1<<APB_CSI2_DPHY_ENABLE_LANE_1_BIT)
#define APB_CSI2_DPHY_ENABLE_LANE_1_DIS       				(0<<APB_CSI2_DPHY_ENABLE_LANE_1_BIT)

#define APB_CSI2_DPHY_ENABLE_LANE_CLK_BIT     				(6)
#define APB_CSI2_DPHY_ENABLE_LANE_CLK_BITS    				(1)
#define APB_CSI2_DPHY_ENABLE_LANE_CLK_MASK    				ARCHI_REG_MASK(APB_CSI2_DPHY_ENABLE_LANE_CLK_BIT,    APB_CSI2_DPHY_ENABLE_LANE_CLK_BITS)
#define APB_CSI2_DPHY_ENABLE_LANE_CLK_ENA     				(1<<APB_CSI2_DPHY_ENABLE_LANE_CLK_BIT)
#define APB_CSI2_DPHY_ENABLE_LANE_CLK_DIS     				(0<<APB_CSI2_DPHY_ENABLE_LANE_CLK_BIT)

#define APB_CSI2_DPHY_RESET_DIG_LOGIC_BIT     				(0)
#define APB_CSI2_DPHY_RESET_DIG_LOGIC_BITS    				(1)
#define APB_CSI2_DPHY_RESET_DIG_LOGIC_MASK    				ARCHI_REG_MASK(APB_CSI2_DPHY_RESET_DIG_LOGIC_BIT,    APB_CSI2_DPHY_RESET_DIG_LOGIC_BITS)
#define APB_CSI2_DPHY_RESET_DIG_LOGIC_NORMAL  				(1<<APB_CSI2_DPHY_RESET_DIG_LOGIC_BIT)
#define APB_CSI2_DPHY_RESET_DIG_LOGIC_RESET   				(0<<APB_CSI2_DPHY_RESET_DIG_LOGIC_BIT)

// Used for LANE CLK, LANE 0 and LANE 1 
#define APB_CSI2_DPHY_HS_COUNTDOWN_BIT        				(0)
#define APB_CSI2_DPHY_HS_COUNTDOWN_BITS       				(8)
#define APB_CSI2_DPHY_HS_COUNTDOWN_MASK       				ARCHI_REG_MASK(APB_CSI2_DPHY_HS_COUNTDOWN_BIT,       APB_CSI2_DPHY_HS_COUNTDOWN_BITS)
#define APB_CSI2_DPHY_HS_COUNTDOWN(val)       				(val<<APB_CSI2_DPHY_HS_COUNTDOWN_BIT)

#define APB_CSI2_DPHY_LANE_CLK_CONT_MODE_BIT  				(4)
#define APB_CSI2_DPHY_LANE_CLK_CONT_MODE_BITS 				(2)
#define APB_CSI2_DPHY_LANE_CLK_CONT_MODE_MASK 				ARCHI_REG_MASK(APB_CSI2_DPHY_LANE_CLK_CONT_MODE_BIT, APB_CSI2_DPHY_LANE_CLK_CONT_MODE_BITS)
#define APB_CSI2_DPHY_LANE_CLK_CONT_MODE_ENA  				(3<<APB_CSI2_DPHY_LANE_CLK_CONT_MODE_BIT)
#define APB_CSI2_DPHY_LANE_CLK_CONT_MODE_DIS  				(0<<APB_CSI2_DPHY_LANE_CLK_CONT_MODE_BIT)

// Used for LANE CLK, LANE 0 and LANE 1 
#define APB_CSI2_DPHY_RX_CALIB_ENABLE_BIT     				(7)
#define APB_CSI2_DPHY_RX_CALIB_ENABLE_BITS    				(1)
#define APB_CSI2_DPHY_RX_CALIB_ENABLE_MASK    				ARCHI_REG_MASK(APB_CSI2_DPHY_RX_CALIB_ENABLE_BIT,    APB_CSI2_DPHY_RX_CALIB_ENABLE_BITS)
#define APB_CSI2_DPHY_RX_CALIB_ENABLE_ENA     				(1<<APB_CSI2_DPHY_RX_CALIB_ENABLE_BIT)
#define APB_CSI2_DPHY_RX_CALIB_ENABLE_DIS     				(0<<APB_CSI2_DPHY_RX_CALIB_ENABLE_BIT)


#endif