add_files -norecurse -scan_for_includes $SRC_COMMON_CELLS_ALL
add_files -norecurse -scan_for_includes $SRC_SOC_INTERCONNECT
add_files -norecurse -scan_for_includes $SRC_LOW_LATENCY_INTERCO
add_files -norecurse -scan_for_includes $SRC_PERIPHERAL_INTERCO
add_files -norecurse -scan_for_includes $SRC_TCDM_INTERCONNECT
add_files -norecurse -scan_for_includes $SRC_ADV_DBG_IF
add_files -norecurse -scan_for_includes $SRC_APB2PER
add_files -norecurse -scan_for_includes $SRC_APB_ADV_TIMER
add_files -norecurse -scan_for_includes $SRC_APB_FLL_IF
add_files -norecurse -scan_for_includes $SRC_APB_GPIO
add_files -norecurse -scan_for_includes $SRC_APB_NODE
add_files -norecurse -scan_for_includes $SRC_APB_INTERRUPT_CNTRL
add_files -norecurse -scan_for_includes $SRC_AXI
add_files -norecurse -scan_for_includes $SRC_AXI_SLICE
add_files -norecurse -scan_for_includes $SRC_AXI_SLICE_DC
add_files -norecurse -scan_for_includes $SRC_TIMER_UNIT
add_files -norecurse -scan_for_includes $SRC_DIV_SQRT_TOP_MVP
add_files -norecurse -scan_for_includes $SRC_FPNEW
add_files -norecurse -scan_for_includes $SRC_JTAG_PULP
add_files -norecurse -scan_for_includes $SRC_RISCV
add_files -norecurse -scan_for_includes $SRC_RISCV_REGFILE_FPGA
add_files -norecurse -scan_for_includes $SRC_CV32E40P
add_files -norecurse -scan_for_includes $SRC_IBEX
add_files -norecurse -scan_for_includes $SRC_IBEX_REGFILE_FPGA
add_files -norecurse -scan_for_includes $SRC_SCM_FPGA
add_files -norecurse -scan_for_includes $SRC_TECH_CELLS_RTL_SYNTH
add_files -norecurse -scan_for_includes $SRC_TECH_CELLS_FPGA
add_files -norecurse -scan_for_includes $SRC_UDMA_CORE
add_files -norecurse -scan_for_includes $SRC_UDMA_UART
add_files -norecurse -scan_for_includes $SRC_UDMA_I2C
add_files -norecurse -scan_for_includes $SRC_UDMA_I2S
add_files -norecurse -scan_for_includes $SRC_UDMA_QSPI
add_files -norecurse -scan_for_includes $SRC_UDMA_SDIO
add_files -norecurse -scan_for_includes $SRC_UDMA_CAMERA
add_files -norecurse -scan_for_includes $SRC_UDMA_FILTER
add_files -norecurse -scan_for_includes $SRC_UDMA_EXTERNAL_PER
add_files -norecurse -scan_for_includes $SRC_HWPE_CTRL
add_files -norecurse -scan_for_includes $SRC_HWPE_STREAM
add_files -norecurse -scan_for_includes $SRC_HW_MAC_ENGINE
add_files -norecurse -scan_for_includes $SRC_RISCV_DBG
add_files -norecurse -scan_for_includes $SRC_REGISTER_INTERFACE
add_files -norecurse -scan_for_includes $SRC_REGGEN_PRIMITIVES
add_files -norecurse -scan_for_includes $SRC_PULP_SOC
add_files -norecurse -scan_for_includes $SRC_UDMA_SUBSYSTEM
add_files -norecurse -scan_for_includes $SRC_FC
add_files -norecurse -scan_for_includes $SRC_COMPONENTS
